### ISSUE TITLE
Support for .ruby-version file in deploy

### ISSUE THREAD

**Issue by mberlanda** [ajgon/opsworks_ruby#103]
I tried to deploy on a new instance a project from last November.

Despite my `.ruby-version` file contains:
```
ruby-2.2.4
```

The version installed on Opsworks is the 2.4.0.
The issue is related to all the implications due to the latest version of ruby.

According to the error backtrace log:
```
Installing ruby_parser 3.8.3
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
 
current directory:
/srv/www/{app-name}/shared/vendor/bundle/ruby/2.4.0/gems/puma-3.6.2/ext/puma_http11
/usr/bin/ruby2.4 -r ./siteconf20170828-16038-uw1rst.rb extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
checking for openssl/bio.h... yes
creating Makefile
 
current directory:
/srv/www/{app-name}/shared/vendor/bundle/ruby/2.4.0/gems/puma-3.6.2/ext/puma_http11
ake "DESTDIR=" clean
 
current directory:
/srv/www/{app-name}/shared/vendor/bundle/ruby/2.4.0/gems/puma-3.6.2/ext/puma_http11
ake "DESTDIR="
compiling http11_parser.c
compiling io_buffer.c
compiling mini_ssl.c
ini_ssl.c: In function ‘get_dh1024’:
ini_ssl.c:90:5: error: dereferencing pointer to incomplete type ‘DH {aka struct
dh_st}’
dh->p = BN_bin2bn(dh1024_p, sizeof(dh1024_p), NULL);
^
```

I managed to fix this particular issue forcing a rails gem version and upgrading the puma gem version in the Gemfile.

Fortunately this project was not so critical, so I had the time to find this solution, however it would be useful to specify the ruby version via .rvm-version or the Custom JSON.

I see that you are referring to it in the [README.md](https://github.com/ajgon/opsworks_ruby#development) but I don't know if this development is in progress or is a _nice to have_ for the future.

Thank you for the great work!

**Comment by ajgon** [comment]
You can configure your Ruby version via `node['ruby-ng']['ruby_version']` as [described here](opsworks-ruby.readthedocs.io/en/latest/attributes.html#stack-attributes). 

Would it solve your problem?

**Comment by mberlanda** [comment]
Hi @ajgon , thank you for your quick reply.

I actually updated my Stack Settings custom json as follows:
```js
{
  "app-name": {
    "global": {
      "environment": "production"
    },
    "framework": {
      "envs_in_console": true
    },
    "appserver": {
      "application_yml": true
    },
    "ruby-ng": {
      "ruby_version": "2.3"
    }
  }
}
```
However, when i connect to the machine via ssh I get the version 2.4 installed:
```
ubuntu@kronos:~$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux-gnu]
```
The default ruby version should be set in [attributes/default.rb](https://github.com/ajgon/opsworks_ruby/blob/master/attributes/default.rb#L6)

I went back to the [JSON configurator](http://opsworks-ruby.rzegocki.pl/configuration-builder) and I noticed that the new version is adding the "deploy" key on top of all the rest of the configuration:
```js
{
  "deploy": {
    "app-name": {
       // the same as above
    }
  }
}  
```
On my new machine, however, still the same output:
```
ubuntu@demeter:~$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux-gnu]
```
I assume that the rest of the configuration is working properly since my `application.yml` is created correctly, despite I get these warnings when I run the rails console:
```
/releases/20170830081416$ RAILS_ENV=production bundle exec rails c
WARNING: Skipping key "SECRET_KEY_BASE". Already set in ENV.
WARNING: Skipping key "SECRET_TOKEN". Already set in ENV.
WARNING: Skipping key "RAILS_ENV". Already set in ENV.
WARNING: Skipping key "HOME". Already set in ENV.
WARNING: Skipping key "USER". Already set in ENV.
Loading production environment (Rails 5.0.5)
```
I am pretty sure I am missing something very trivial...

**Comment by ajgon** [comment]
Yes, `ruby-ng` doesn't belong to `app-name` scope :) So you need to update your stack.json to:

```json
{
  "ruby-ng": {
    "ruby_version": "2.3"
  },
  "app-name": {
    "global": {
      "environment": "production"
    },
    "framework": {
      "envs_in_console": true
    },
    "appserver": {
      "application_yml": true
    }
  }
}
```

and everything should work as expected.

**Comment by mberlanda** [comment]
WOW. I got it! Would it be possible to add to the JSON Configurator - just to prevent other people to make the same error ? Is it mandatory the "deploy" key on top of the configuration?

Thank you very much (again)!

**Comment by ajgon** [comment]
Yes, this is to keep compatibility with old Chef 11 stack. I altered the JSON in my previous comment.

**Comment by mberlanda** [comment]
Perfect! Thank you then
