### ISSUE TITLE
Rails: assets:precompile

### ISSUE THREAD

**Issue by ajgon** [ajgon/opsworks_ruby#12]

**Comment by cickes** [comment]
Unable to override assets_precompile.  Thoughts?  

Including the following custom json in layer settings
```
{
  "app-being-deployed-shortname":  : {
      "framework": {
        "assets_precompile": false
    }
}
```  
This is not overriding the default "true".  In turn, I receive the following error.  
  
```
================================================================================
Error executing action `run` on resource 'execute[assets:precompile]'
================================================================================
 
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /usr/local/bin/bundle exec rake assets:precompile ----
STDOUT: 
STDERR: rake aborted!
Don't know how to build task 'assets:precompile' (see --tasks)
```

**Comment by ajgon** [comment]
Which framework do you user? Rails?

**Comment by cickes** [comment]
Yes, Rails framework.  I did not specify this in any attributes though.  Did I miss something?  Should "rails" replace "framework" in the custom json?

**Comment by ajgon** [comment]
No, your JSON is correct, I'll try to debug this issue today and let you know what's going on...

**Comment by ajgon** [comment]
Ok, I tried to reproduce your error, but with no luck. I also added tests to cover up this case - no luck either. Can you paste me a full Stack JSON you are using (with sensitive data redacted)?

**Comment by cickes** [comment]
```
{
  "appname": {
    "framework": {
      "assets_precompile": false
    }
  },
  "applications": ["appname"] 
}
```
Very basic install, essentially testing.  Using Rails API, if that matters.  
`rails new appname --api`

**Comment by ajgon** [comment]
Ok, I nailed the issue - something changed in `Chef` API (again). I know how to fix it, but it's bigger issue, so I'll fix it on weekend.

Thanks for catching this!

**Comment by ajgon** [comment]
Ok, I don't know how I didn't notice it... but we were missing the `'deploy'` keyword in the Stack JSON 😊 Because that was the original format of Chef 11 Stack for Amazon.

So, your config should state:

```json
{
  "deploy": {
    "appname": {
      "framework": {
        "assets_precompile": false
      }
    },
    "applications": ["appname"] 
  }
}
```

and everything would work as expected.
