### ISSUE TITLE
Bundle Config

### ISSUE THREAD

**Issue by kschutt** [ajgon/opsworks_ruby#128]
Hello,

Is there a way to run a custom `bundle config` command before running `bundle install`? 

We are using a source for one of our gems that requires a login, but we don't want to check the credentials into source code, nor do we want the credentials to show up in the `Gemfile.lock` file.

**Comment by ajgon** [comment]
Hey,

Not at the moment, but you can easily alter the recipe to do this for you in [libraries/helpers.rb](https://github.com/ajgon/opsworks_ruby/blob/4cc324cec85acd8c06c2f63138fef32bf8c9aeee/libraries/helpers.rb#L98). You can do something like this:

```ruby
def perform_bundle_install(shared_path, envs = {})
  bundle_path = "#{shared_path}/vendor/bundle"

  execute 'bundle_config' do
    command "/usr/local/bin/bundle config --extra-params"
    user node['deployer']['user'] || 'root'
    group www_group
    environment envs
    cwd release_path
  end

  execute 'bundle_install' do
    command "/usr/local/bin/bundle install --deployment --without development test --path #{bundle_path}"
    user node['deployer']['user'] || 'root'
    group www_group
    environment envs
    cwd release_path
  end
end
```
