### ISSUE TITLE
No default scm provider

### ISSUE THREAD

**Issue by waghanza** [ajgon/opsworks_ruby#129]
Hi,

I've used the [JSON Configurator](http://opsworks-ruby.rzegocki.pl/configuration-builder) to write **Custom JSON**.

As I'm using **git** as `scm_provider`, I have not specified any provider on my **Custom JSON**.

However I have the following errors, while starting my instance :

> There is no supported Scm driver for given configuration

What have I to specify ?

Regards,

**Comment by sebykrueger** [comment]
I am seeing the exact same error message. However, I am trying to use S3 as the SCM, and it appears that opsworks_ruby only supports deployment from GIT and not S3 as there is no S3 provider class. Hence the drivers_scm_factory.rb class throws the error. Are there plans to support S3 as a SCM as well at some point?

**Comment by ajgon** [comment]
@sebykrueger Actually, yes - it's a good idea. However I'm leaving for a vacation so probably I'll implement it somewhere in a middle of February.

**Comment by ajgon** [comment]
@waghanza Can you paste me a generated JSON which you use (with all sensitive data removed)?

**Comment by waghanza** [comment]
@ajgon  here it is, the application short name is **api**
~~~json
{
	"layer": "****"
	"deploy": {
		"api": {
			"database": {
				"database": "*****",
				"password": "****",
				"adapter": "****",
				"port": "***",
				"host": "****",
				"username": "***"
			},
			"framework": {
				"adapter": "null"
			},
			"global": {
				"deploy_dir": "***"
			},
			"scm": {
				"repository": "git@github.com:....",
				"revision": "master",
				"scm_provider": "git"
			}
		}
	}
}
~~~
@sebykrueger I plan to migrate from **git**  to **s3** deployment in a near future, so I can test the adapter (if created or create one)

**Comment by sebykrueger** [comment]
The S3 bucket option is important for CodePipeline to work in us-east-1 as well. It's a common recommendation to store deployed code as zip bundles in S3. Would be great to have that feature available.

**Comment by ajgon** [comment]
@waghanza It's probably a bug. However if you use GIT as an SCM, you don't have to configure it in JSON file. You can use OpsWorks admin panel for that and it should work out of the box (just don't forget to remove `scm` key from your JSON file).

**Comment by waghanza** [comment]
@ajgon I tried without providing the key **scm_provider**, but seems to be the same

**Comment by waghanza** [comment]
I've found a solution.

I have to list applications in my stack json.
