### ISSUE TITLE
Implement S3 support for SCM provider

### ISSUE THREAD

**Issue by ajgon** [ajgon/opsworks_ruby#133]

**Comment by kschutt** [comment]
I second this. We would prefer to use an archive that includes all the precompiled assets and bundled gems without having to check it into Git.

**Comment by porter77** [comment]
+1

**Comment by kschutt** [comment]
@ajgon thanks! this is awesome! do we have to set up the `source` within the Custom JSON for the S3 archive or can we use the Application Source setup in OpsWorks? We don't really want to store the AWS Access Key in plain text (although we could just create restricted AWS creds)

**Comment by ajgon** [comment]
@kschutt You can use OpsWorks setup without any problems. However I found a little bug in the implementation, and fixing it right now, so please - hold on with experiments for few minutes :)

**Comment by kschutt** [comment]
@ajgon no problem, will hold off

**Comment by kschutt** [comment]
@ajgon we already had a test server getting setup when you replied, but it did fail. Can you detail the bug here? Does it have to do with `No such file or directory` in `drivers_source_s3.rb#49`?

**Comment by ajgon** [comment]
No, this is not related - the problem which I'm working on is with creating "dummy" git repository for file to make `chef deploy` actually work.

It looks like the cookbook can't fetch file from S3 for whatever reason - are you sure, the given AWS keys have access to it, and the path is correct?

**Comment by kschutt** [comment]
I think it has to do with the `File.join` and not the S3 archive since we do have access to it

```
No such file or directory @ rb_file_s_rename - (/tmp/rest-client20180316-1840-lel1cw, /tmp/opsworks_ruby20180316-1840-1xqhq8h/archive/circleci-2.0-workflows/circleci-2.0-workflows.tar.gz)
```

**Comment by ajgon** [comment]
Interesting, I'll investigate it further in a minute...

**Comment by ajgon** [comment]
Deployed to both issues (yours and mine) here: https://github.com/ajgon/opsworks_ruby/commit/9373173db012fb5af02c9e622bef12312909e589. Waiting for travis tests to pass, but you can check it right now if you like.

**Comment by kschutt** [comment]
Awesome, thanks for the update. We tried this new version, but now we are receiving the following error:

```
---- Begin output of git ls-remote "/tmp/opsworks_ruby20180317-9248-1rd9m9k/archive.d" "HEAD" ----
STDOUT: 
STDERR: fatal: '/tmp/opsworks_ruby20180317-9248-1rd9m9k/archive.d' does not appear to be a git repository
fatal: Could not read from remote repository.
 
Please make sure you have the correct access rights
and the repository exists.
---- End output of git ls-remote "/tmp/opsworks_ruby20180317-9248-1rd9m9k/archive.d" "HEAD" ----
```

**Comment by ajgon** [comment]
Yeah, that was the second issue I was fixing... should be ok with the newest version. When you SSH to the machine, what permissions this directory has?

**Comment by kschutt** [comment]
I think that folder gets removed on rollback so I don't have the permissions but `tmp` is `drwxrwxrwt`

**Comment by kschutt** [comment]
I repulled the latest and it works now. Awesome work, thanks!
