### ISSUE TITLE
Using private repository

### ISSUE THREAD

**Issue by waghanza** [ajgon/opsworks_ruby#135]
Hi,

Using [configuration tool](http://opsworks-ruby.rzegocki.pl/configuration-builder) to create my `CustomJson`, I have not seen how to file a **deploy key** to use a _private_ repository.

Is this feature available ?

Regards,

**Comment by ajgon** [comment]
Hey, I’m sorry but I’m currently traveling and can’t check it on my mobile, but if I recall correctly - you can do this in opsworks panel. There should be a text area to paste key when configuring git repo.

**Comment by ajgon** [comment]
There is also a ‘app['scm']['ssh_key']’ configuration option if you want to do this manually via JSON file - you can find more info here: https://opsworks-ruby.readthedocs.io/en/latest/attributes.html#attributes

**Comment by waghanza** [comment]
of course

my feedback is more about the [configuration tool](http://opsworks-ruby.rzegocki.pl/configuration-builder) 

It does not expose the **ssh_key** option

**Comment by ajgon** [comment]
Yeah, it must be a bug in configurator - it has this option configured, but it doesn’t show it for whatever reason. I’ll fix that when I get back :)

**Comment by ajgon** [comment]
Fixed the configuration, thanks for catching this up! :)
