### ISSUE TITLE
Disabling database migration using cloudformation

### ISSUE THREAD

**Issue by waghanza** [ajgon/opsworks_ruby#139]
Hi,

Migrate option support `true` / `false` values.

Those **boolean** are supported according to `json ` format, in *Custom JSON*.

However, **boolean** values are **NOT** supported on ` Cloudformation`.

So, when we are using `Cloudformation` we can not _disable_ database migration process.

Perhaps, we can allow empty value to _disable_ migrations.

Regards,

**Comment by ajgon** [comment]
Unfortunatelly, I have zero experience with cloudformation. The extension was intended for AWS OpsWorks.

**Comment by waghanza** [comment]
Sure, this stuff is on **AWS** `Cloudformation` side ;-)

But in order to disable (mimic `false` behavior) can't we use a null (string) ?

**Comment by ajgon** [comment]
You can always alter the Custom JSON and set it to `null` instead of `false` by hand. The cookbook code doesn't check explictly for false, and `nil` in ruby is considered as `false` so you should be good :)
