### ISSUE TITLE
Bundler not respecting Ruby version

### ISSUE THREAD

**Issue by dmward** [ajgon/opsworks_ruby#141]
I've set the ruby_version for ruby-ng to "2.1" in my config. It looks to download the 2.1 version just fine, but when bundler runs, it is using Ruby 2.4. This is causing me some grief as many gems (for my Rails 3.2 app) will not build under Ruby 2.4.

I would expect the version below to be "2.1.0" and not "2.4.0":
```
Bundler::GemRequireError: There was an error while trying to load the gem 'devise'.
Gem Load Error is: ActiveSupport::Duration can't be coerced into Integer
Backtrace for gem load error is:
/srv/www/pt/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/numeric/time.rb:50:in `*'
```

This is happening during my Opsworks "setup" for an instance. I can attach the entire logfile if that would help.

Thanks.

**Comment by ajgon** [comment]
Odd, that shouldn't be the case. Are you sure, you don't have a ruby version set to `2.4` somewhere else? Have you tried to freeze ruby version in `Gemfile` by adding the 

```ruby
ruby "2.1.0"
```

line to your Gemfile?

**Comment by inopinatus** [comment]
Looks like the context in which Chef runs sets a path that gets in the way of correct ruby versions.

For example, if I `bundle exec` from a `before_symlink.rb` then I get 

    Bundler::RubyVersionMismatch: Your Ruby version is 2.3.1, but your Gemfile specified 2.3.7.

**Comment by ajgon** [comment]
How do you install Ruby? Via ruby_ng or some other tool? Can you paste your custom JSON (with sensitive data removed) ?
