### ISSUE TITLE
Environment variables fail to update on clean restart

### ISSUE THREAD

**Issue by kschutt** [ajgon/opsworks_ruby#142]
Hello,

This is more informational than an actual bug, but it caused us a ton of headaches.

Here is our setup:

```
Appserver: Unicorn
Env: Figaro (app.yml)
```

It seems that https://github.com/ajgon/opsworks_ruby/commit/e46d5fee3c9d469b3e41575d3c624b8be843da16#diff-371a459048a25bfa4ce43154b9d9fd55R6 introduced a change for all appservers where it defines all the environment variables in the script as `ENV['VAR1']`. This is fine because the [`after_deploy`](https://github.com/ajgon/opsworks_ruby/blob/master/libraries/drivers_appserver_base.rb#L21) method does a `stop-start` on the appserver itself.

However, if we change the `after_deploy` to be a [`clean-restart`](https://github.com/ajgon/opsworks_ruby/blob/master/templates/default/appserver.service.erb#L75) using `USR2` instead, then any changes to the `ENV` variables in OpsWorks are not picked up. This is because the user's `ENV` isn't changed with a `clean-restart` which override any variables set in `application.yml`. This was visible when launching `rails console` with errors similar to below:

```
WARNING: Skipping key "SECRET_KEY_BASE". Already set in ENV.
```

The solution for us was to remove the `ENV` setters in the `appserver.service.erb` and let Unicorn pick up the variables from `application.yml` which is updated on deployment.

*Note:* This is specifically for -updating- an environment variable's value. Any -new- environment variables are unaffected because the `clean-restart`'d Unicorn process loads them from the `application.yml`.

**Comment by ajgon** [comment]
Thank you for this feedback! I'll add it to "Troubleshoot" section of the documentation.
