### ISSUE TITLE
Thin / Puma / Unicorn app drivers are broken on master

### ISSUE THREAD

**Issue by nathan-appere** [ajgon/opsworks_ruby#144]
@ajgon it seems that https://github.com/ajgon/opsworks_ruby/commit/4cc324cec85acd8c06c2f63138fef32bf8c9aeee#diff-6422d4a24703f8d709ede2e802a59c75 broke `appserver_command` by adding extra `\`, which means that the variables are not interpolated any more when trying to use the services.

**Comment by ajgon** [comment]
Fixed in #146
