### ISSUE TITLE
Deploy hooks missing instance attributes

### ISSUE THREAD

**Issue by kpheasey** [ajgon/opsworks_ruby#154]
It doesn't appear that instance attributes are available in the deploy hooks: https://docs.aws.amazon.com/opsworks/latest/userguide/attributes-json-opsworks-instance.html

Because of this, the only way to identify an instance is by the ec2 instance id.  This makes running commands on a single instance in a layer very difficult.  If an instance is replaced, the deployment hooks must be updated.

Any suggestions on how to run a command from a deployment hook on a single instance of a layer?

I was looking into how to add this, but all I see in terms of context is self; https://github.com/ajgon/opsworks_ruby/blob/master/recipes/deploy.rb#L66.  If you could point me i the right direction, I'll create a PR for it.

**Comment by olbrich** [comment]
You can get at the databags from the the hooks by doing something like 
```
instance = new_resource.search(:aws_opsworks_instance, 'self:true')
```

Which will get you the instance the hook is running on, but it's problematic to only run a command on one server in a layer.  You can pick the first one from all of the instances and run your command on that if it happens to also be the current one, but that will fail if the first server in your layer is shut down.

You might want to consider doing this sort of thing during the 'configure' part of the lifecycle, which will happen any time an instance comes online or leaves your layer.

**Comment by kpheasey** [comment]
@olbrich Thanks for the snippet.

It's not mission critical stuff.  Just alerting Rollbar to a deployment and things like that.

**Comment by olbrich** [comment]
@kpheasey Yeah, I do the same thing with NewRelic.
