### ISSUE TITLE
deployer doesn't have name metadata, not compatible with Chef 12

### ISSUE THREAD

**Issue by inopinatus** [ajgon/opsworks_ruby#155]
During setup I'm getting

    [2018-05-20T05:22:27+00:00] ERROR: Could not read /var/chef/cookbooks/deployer into a Chef object: Cookbook loaded at path(s) [/var/chef/cookbooks/deployer] has invalid metadata: The `name' attribute is required in cookbook metadata

and indeed the release version (0.1.1, from 2012, see https://supermarket.chef.io/cookbooks/deployer) of deployer doesn't have `name` in its `metadata.rb`. I have no idea how to fix this without forking deployer.

**Comment by olbrich** [comment]
How has this not broken this cookbook until now? 

@ajgon you might be able to specify the git repo master branch in the Berksfile.

**Comment by ajgon** [comment]
Looks like, only `metadata.rb` doesn't contain this field. In cookbook there is also `metadata.json` file which has this field properly set up. Apparently Chef 12 favors `metadata.rb`.

**Comment by omenking** [comment]
Is this in Master yet?
I just ran into this issue.
