### ISSUE TITLE
Syntax error in libraries/archive.rb:62

### ISSUE THREAD

**Issue by zave** [ajgon/opsworks_ruby#160]
I'm running this recipe on a Vagrant box (Ubuntu 1604), from a Mac OSX 10.13.4 host. I've done nothing to the recipes yet, other than berks install the dependencies. I'm getting this error:

### SyntaxError: /tmp/vagrant-chef/79255ed364890f68b80313f13fbf1fed/cookbooks/opsworks_ruby/libraries/archive.rb:62: syntax error, unexpected '.'
        find_mime_matches(io)&.first
                               ^
/tmp/vagrant-chef/79255ed364890f68b80313f13fbf1fed/cookbooks/opsworks_ruby/libraries/archive.rb:85: syntax error, unexpected '.'
      end&.first || mime_type

Any suggestions?

**Comment by ajgon** [comment]
Which version of ruby do you use in your installation? `opsworks_ruby` is designed to be run under ruby 2.3 or later.

**Comment by zave** [comment]
Resolved. I guess I was using an incorrect version of Ruby. I blew it away and started over, and it worked.
