### ISSUE TITLE
no way to specify port for appserver only instances

### ISSUE THREAD

**Issue by phongsi** [ajgon/opsworks_ruby#162]
### Expected Behavior
Separate webserver and  appservers on different hosts.

### Actual Behavior
Unable to specify null webserver and have appserver serve on a port. current puma defaults to unix socket.

I have a working branch i'd like to merge in if this is something you agree with.
[commit](https://github.com/phongsi/opsworks_ruby/commit/6f520678667104cbd08c83344b619e98e9eefa24)
One reason one might want to separate the webserver and appserver on different machines is for regulatory compliance. Another reason for the null webserver is maybe one has no static resources and everything gets passed to the appserver or routing is done through the load balancer layer, so a webserver adds no value.

**Comment by ajgon** [comment]
Looking good 👍 . Can you also add this to other appservers (thin and unicorn) and document this parameter in `docs/` (why it's there and what it does?)

**Comment by phongsi** [comment]
yo. sorry for late reply. Will do.
