### ISSUE TITLE
Allow to override the adapter part of the generated database.yml

### ISSUE THREAD

**Issue by fpbouchard** [ajgon/opsworks_ruby#165]
Our postgresql server has the postgis extension installed, and we are using [`activerecord-postgis-adapter`](https://github.com/rgeo/activerecord-postgis-adapter) as the adapter. It is a subclass of postgresql that requires the adapter in database.yml to be set as `postgis`. Unfortunately it seems that this use case is hard to support in the current implementation. We are using a standard RDS setup but I can't override the adapter in the node configuration.

Any idea on how to do this?

**Comment by ajgon** [comment]
You can do this fairly easy, by adding a new db engine to your opsworks_ruby cookbook in `libraries/drivers_db_postgis.rb` with content:
```ruby
# frozen_string_literal: true

module Drivers
  module Db
    class Postgis < Base
      adapter :postgis
      allowed_engines :postgis
      packages debian: 'libpq-dev', rhel: 'postgresql96-devel'
    end
  end
end
```

However I'm going to add it to new release of `opsworks_ruby` as well.

**Comment by fpbouchard** [comment]
Nice, thanks!

May I suggest also installing the `libgeos-dev` for debian and `libgeos-devel` for rhel packages to the driver? This allows full `rgeo` compatibility.
