### ISSUE TITLE
Unable to set specific Ruby version

### ISSUE THREAD

**Issue by krzkrzkrz** [ajgon/opsworks_ruby#172]
Not sure if Im reading https://github.com/ajgon/opsworks_ruby/blob/master/docs/source/attributes.rst correctly. But I've tried many variations of setting ruby version in my custom json. And all I get is the same error (described below) saying `Your Ruby version is 2.3.7`, when I specifically defined it as `2.3.6`

Im using the Amazon Linux instance
App short name is `api`

### Expected Behavior

Should be setup with 2.3.6

### Actual Behavior

Still looking for Ruby 2.3.7

### Custom JSON

```json
{
    "deploy": {
        "api": {
            "global": {
                "ruby-version": "2.3.6"
            },
            "opsworks": {
                "ruby_version": "2.3"
            },
            "ruby": {
                "patch_version": "6"
            },
            "ruby-version": "2.3.6",
            "database": {
                "adapter": "postgresql",
                "encoding": "unicode",
                "database": "<actual_db_name_here>",
                "pool": 5,
                "username": "<actual_username>",
                "password": "<actual_pwd>",
                "host": "<actual_url>",
                "port": 5432
            }
        },
        "global": {
            "ruby-version": "2.3.6"
        },
        "opsworks": {
            "ruby_version": "2.3"
        },
        "ruby": {
            "patch_version": "6"
        },
        "ruby-version": "2.3.6"
    },
    "global": {
        "ruby-version": "2.3.6"
    },
    "opsworks": {
        "ruby_version": "2.3"
    },
    "ruby": {
        "patch_version": "6"
    },
    "ruby-version": "2.3.6"
}
```

### Chef log including error

```
================================================================================
Error executing action `run` on resource 'execute[bundle_install]'
================================================================================
 
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '18'
---- Begin output of /usr/local/bin/bundle install --deployment --without development test --path /srv/www/api/shared/vendor/bundle ----
STDOUT: `/root` is not writable.
Bundler will use `/tmp/bundler/home/root' as your home directory temporarily.
Your Ruby version is 2.3.7, but your Gemfile specified 2.3.6
STDERR: 
---- End output of /usr/local/bin/bundle install --deployment --without development test --path /srv/www/api/shared/vendor/bundle ----
Ran /usr/local/bin/bundle install --deployment --without development test --path /srv/www/api/shared/vendor/bundle returned 18
```

**Comment by olbrich** [comment]
I think the cookbook installs ruby from the ruby-ng packages.  Those packages only track the major and minor version, so you always get the latest released patch version with them.  You can really only define your version as `2.3`.  There are things you can do in your Gemfile to make this work properly, you can try entering a line like:

```
ruby "~> #{File.read(File.join(__dir__, '.ruby-version')).to_f}.0"
```
Which will allow the patch version of ruby to float to whatever is installed on the machine.

or possibly
```
ruby RUBY_VERSION
```
Which will use the version of ruby used to run bundler, whatever it happens to be.

If you want finer grained control of ruby versions, you are going to have to use something like ruby-build to install it from source, which will add about 10 minutes of time to your initial setup.

In my experience, the packages work well and the patch releases aren't very risky.  Most of the time you will just get security patches if you follow the latest.

**Comment by krzkrzkrz** [comment]
Where is `.ruby-version` defined? Or is this something I need to create? What should be in the file exactly?

**Comment by krzkrzkrz** [comment]
Im using `rbenv` but dont see `.ruby-version` in the root dir. In any case, in Gemfile, I now have

```
ruby '~> 2.3.0'
```

Seems to work. But I think this should also be pointed out in the README somewhere
