### ISSUE TITLE
Integrating jemalloc

### ISSUE THREAD

**Issue by krzkrzkrz** [ajgon/opsworks_ruby#175]
I thought I'd mention this here. Online, seen a few mentions on performance gains using a different memory allocator for Ruby.

@olbrich you mentioned (at https://github.com/ajgon/opsworks_ruby/issues/173) you had your own recipe/templates/metadata/etc for the jemalloc. Do you mind sharing the fully coded implementation here?

On AWS, are you using the Amazon linux or other instance type (i.e. Ubuntu LTS)?

Would be great to know how you managed to get this going with opsworks_ruby

**Comment by olbrich** [comment]
@krzkrzkrz that snippet was pretty much the entire solution.  
FYI, I use ubuntu LTS, not sure if Amazon linux is any different.

**Comment by krzkrzkrz** [comment]
Unfortunately, the package managers at Amazon linux AMIs doesnt have `libjemalloc-dev`

Instead, I'm using this cookbook https://github.com/priestjim/chef-jemalloc/blob/master/recipes/default.rb, via cookbook 'jemalloc'

Managed to install jemalloc. In `/usr/lib`, I can see the following files:

```
libjemalloc.a
libjemalloc.so
libjemalloc.so.2
libjemalloc_pic.a
```

In `/recipes/setup.rb`, Im following something similar to what you have:

```
# Install jemalloc for better memory management
include_recipe 'jemalloc::default'

ruby_block "add LD_PRELOAD" do
  block do
    file = Chef::Util::FileEdit.new("/etc/environment")
    file.insert_line_if_no_match("/LD_PRELOAD/", "LD_PRELOAD=/usr/lib/libjemalloc.so")
    # file.insert_line_if_no_match("/LD_PRELOAD/", "LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1")
    file.write_file
  end
end
```

Running Deployments -> Run command -> Setup, in the OpsWorks UI, returns without any problems. But when I ssh into the instance and run `ruby -r rbconfig -e "puts RbConfig::CONFIG['LIBS']"`. I only get

```
-lpthread -ldl -lcrypt -lm
```

Its missing the `-ljemalloc` flag, which means, Ruby isnt compiled/running with jemalloc

Btw, I am also following https://www.levups.com/en/blog/2017/optimize_ruby_memory_usage_jemalloc_heroku_scalingo.html
while putting fragments of information together from your recipe and from other parts of the web

Any suggestions will help

**Comment by krzkrzkrz** [comment]
@olbrich If you ssh into one of your instances and type `ruby -r rbconfig -e "puts RbConfig::CONFIG['LIBS']"`. I am curious. What output do you see?

**Comment by krzkrzkrz** [comment]
Reading https://docs.chef.io/resource_ruby_block.html and https://github.com/jemalloc/jemalloc/wiki/Getting-Started

`jemalloc-config --libdir` returns `/usr/lib`
`jemalloc-config --revision` returns `2`

Putting above together. In `/recipes/setup.rb`, I have:

```
ruby_block "add LD_PRELOAD" do
  block do
    ENV['LD_PRELOAD'] = '/usr/lib/libjemalloc.so.2'
  end
end
```

Restarted the instance. But 

```
$ ruby -r rbconfig -e "puts RbConfig::CONFIG['LIBS']"
-lpthread -ldl -lcrypt -lm
```

Still no `-ljemalloc` flag. Not sure what I'm doing wrong

**Comment by olbrich** [comment]
so the rbconfig thing won't work because you didn't compile ruby with that flag.  It's not a great way to tell if jemalloc is installed actually.  Try ssh'ing to one of the machines, get into `irb` and doing something like this...

```
$> MALLOC_CONF=stats_print:true ruby -e "exit"
```

That will print out a lot of statistics if it's properly installed.

What version of jemalloc is reported this way?  I currently have 3.6.0 installed.

**Comment by krzkrzkrz** [comment]
In my recipe, I have:

```
include_recipe 'jemalloc::default'

ruby_block "add LD_PRELOAD" do
  block do
    ENV['LD_PRELOAD'] = '/usr/lib/libjemalloc.so.2'
  end
end
```

I SSH'd into an instance, went into `irb` and did:

```
irb(main):007:0> MALLOC_CONF=stats_print:true ruby -e "exit"
SyntaxError: (irb):7: syntax error, unexpected tIDENTIFIER, expecting end-of-input
MALLOC_CONF=stats_print:true ruby -e "exit"
                                 ^
        from /usr/bin/irb:11:in `<main>'
```

Is that expected? It looks like wrong syntax

**Comment by krzkrzkrz** [comment]
Does it have to be run inside `irb`?

If I SSH into the instance and just type `MALLOC_CONF=stats_print:true ruby -e "exit"`, I get:

```
[root@avocado ec2-user]# MALLOC_CONF=stats_print:true ruby -e "exit"
___ Begin jemalloc statistics ___
Version: 3.3.1-0-g9ef9d9e8c271cdf14f664b871a8f98c827714784
Assertions disabled
Run-time option settings:
  opt.abort: false
  opt.lg_chunk: 22
  opt.dss: "secondary"
  opt.narenas: 1
  opt.lg_dirty_mult: 3
  opt.stats_print: true
  opt.junk: false
  opt.quarantine: 0
  opt.redzone: false
  opt.zero: false
  opt.tcache: true
  opt.lg_tcache_max: 15
CPUs: 1
Arenas: 1
Pointer size: 8
Quantum size: 16
Page size: 4096
Min active:dirty page ratio per arena: 8:1
Maximum thread-cached size class: 32768
Chunk size: 4194304 (2^22)
Allocated: 4445224, active: 5500928, mapped: 12582912
Current active ceiling: 8388608
chunks: nchunks   highchunks    curchunks
              3            3            3
huge: nmalloc      ndalloc    allocated
            0            0            0

arenas[0]:
assigned threads: 1
dss allocation precedence: disabled
dirty pages: 1343:164 active:dirty, 1 sweep, 1 madvise, 256 purged
            allocated      nmalloc      ndalloc    nrequests
small:        2692136        37374         7480        57026
large:        1753088          172           49          276
total:        4445224        37546         7529        57302
active:       5500928
mapped:       8388608
bins:     bin  size regs pgs    allocated      nmalloc      ndalloc    nrequests       nfills     nflushes      newruns       reruns      curruns
            0     8  501   1        11944         1550           57         1586           18    1            3            0            3
            1    16  252   1        30400         1900            0         2053           19    0            8            0            8
            2    32  126   1       124800         4000          100         7102           40    1           31            3           31
            3    48   84   1       616896        17976         5124        21181          214   61          207           29          207
            4    64   63   1        95872         1667          169         4678           29    3           24            9           24
            5    80   50   1       142320         2250          471         4180           53   10           37           38           36
            6    96   84   2        99360         1050           15         1264           15    2           13            0           13
            7   112   72   2        25648          288           59          313            6    2            4            0            4
            8   128   63   2        55936          470           33          604           10    2            8            1            7
            9   160   51   2       315520         2034           62         5233           46    2           39            1           39
           10   192   63   3        38784          250           48          300            6    3            5            1            4
           11   224   72   4       274176         1224            0         1306           17    0           17            0           17
           12   256   63   4        38400          218           68          233            6    4            3            0            3
           13   320   63   5        95680          406          107          463           10    4            6            0            5
           14   384   63   6        58368          219           67          207            5    3            4            1            3
           15   448   63   7       109312          283           39          314            5    2            5            0            4
           16   512   63   8        27136          107           54           83            5    4            1            0            1
           17   640   51   8        90240          658          517         5486           18   11            8           15            7
           18   768   47   9        53760          116           46          108            4    4            3            1            2
           19   896   45  10        51968          100           42           54            4    3            2            0            2
           20  1024   63  16        36864          100           64           50            4    4            1            0            1
           21  1280   51  16        89600          113           43           75            4    3            2            0            2
           22  1536   42  16        46080           73           43           40            3    3            1            0            1
           23  1792   38  17        34048           56           37           30            3    4            1            0            1
           24  2048   65  33        36864           81           63           30            3    4            1            0            1
           25  2560   52  33        51200           91           71           34            3    4            1            0            1
           26  3072   43  33        33792           53           42           14            2    4            1            0            1
           27  3584   39  35         7168           41           39            5            2    4            2            0            1
large:   size pages      nmalloc      ndalloc    nrequests      curruns
         4096     1           12            0           15           12
         8192     2           23            1          124           22
        12288     3           11            1           11           10
        16384     4          118           43          118           75
[1]
        24576     6            1            0            1            1
[1]
        32768     8            3            1            3            2
        36864     9            2            2            2            0
[10]
        81920    20            1            0            1            1
[235]
      1048576   256            1            1            1            0
[762]
--- End jemalloc statistics ---
```

**Comment by krzkrzkrz** [comment]
Yeap, jemalloc is installed. But does it mean jemalloc is now the memory allocator for Ruby? As in, is Ruby utilizing it now?

**Comment by krzkrzkrz** [comment]
I did a little test. My recipe has:

```
include_recipe 'jemalloc::default'
```

I removed

```
ruby_block "add LD_PRELOAD" do
  block do
    ENV['LD_PRELOAD'] = '/usr/lib/libjemalloc.so.2'
  end
end
```

SSH'd into the instance. And typed `MALLOC_CONF=stats_print:true ruby -e "exit"`

I got the same output. Which means, yeap its installed. But is Ruby using it?

**Comment by krzkrzkrz** [comment]
Reading https://www.levups.com/en/blog/2017/optimize_ruby_memory_usage_jemalloc_heroku_scalingo.html

I noticed this

> The solution we need follows the 12factor methodology by storing the configuration in the environment. We’ll still be able to tell Ruby to load and use jemalloc, but the command line won’t change.
> The LD_PRELOAD environment variable is looked up by MRI to determine which additional libraries it needs to preload. If the jemalloc lib is present, it will use it instead of malloc. It will work with bundle exec ruby as well as with a gem executable such as rubocop orsidekiq.

So the key is to have Ruby load jemalloc via the `LD_PRELOAD` environment variable. In the context of Rails. If one were using [dotenv](https://github.com/bkeepers/dotenv). Would this mean, storing `LD_PRELOAD` in the Rails root dir, inside `.env`?

Or is the article suggesting to have it as UNIX/shell environment variable?

I notice, you are storing `LD_PRELOAD` in `/etc/environment` (which indicates a UNIX/shell environment variable). But I wanted to make sure. If so, for my case. Is having `ENV['LD_PRELOAD'] = '/usr/lib/libjemalloc.so.2'` enough?

**Comment by krzkrzkrz** [comment]
Hmmm, I see. I guess your approach makes sense then. I made a few changes. I now have:

```
include_recipe 'jemalloc::default'

ruby_block "add LD_PRELOAD" do
  block do
    jemalloc_libdir   = shell_out('jemalloc-config --libdir').stdout.chomp
    jemalloc_revision = shell_out('jemalloc-config --revision').stdout.chomp

    file = Chef::Util::FileEdit.new('/etc/environment')
    file.insert_line_if_no_match('/LD_PRELOAD/', "LD_PRELOAD=#{jemalloc_libdir}/libjemalloc.so.#{jemalloc_revision}")
    file.write_file
  end
end
```

`#{jemalloc_libdir}/libjemalloc.so.#{jemalloc_revision}"` interprets to `/usr/lib/libjemalloc.so.2`

But one thing I noticed. In OpsWorks UI. Every time `Running Deployments -> Run command -> Setup` is run. In `/etc/environments`, I see duplicated entries. As in:

```
LD_PRELOAD=/usr/lib/libjemalloc.so.2
LD_PRELOAD=/usr/lib/libjemalloc.so.2
LD_PRELOAD=/usr/lib/libjemalloc.so.2
etc
```

Not sure if `insert_line_if_no_match` is working correctly or if Im doing something wrong..

Could you check your `/etc/environments` to confirm if behaviour is the same. If it isnt. What am I doing wrong on my end?

**Comment by krzkrzkrz** [comment]
Ok figured it out. Seems to work with:

```
environment_path = '/etc/environment'
ld_preload_grep  = /LD_PRELOAD/

ruby_block "add LD_PRELOAD" do
  block do
    file = Chef::Util::FileEdit.new(environment_path)
    file.insert_line_if_no_match(ld_preload_grep, "LD_PRELOAD=#{jemalloc_libdir}/libjemalloc.so.#{jemalloc_revision}")
    file.write_file
end
```

The main difference being `/LD_PRELOAD/` instead of `"/LD_PRELOAD/"`. Not sure how you got it working with double quotes. I had to remove my quotes

**Comment by krzkrzkrz** [comment]
Will be closing this now, since issue is resolved. But feel free to leave your feed back on the `""` difference

**Comment by olbrich** [comment]
@krzkrzkrz confirmed that I am getting repeated lines in my `/etc/environment`.  It's not clear why this isn't working as expected.

**Comment by krzkrzkrz** [comment]
Thanks for checking

**Comment by naveenanilabs** [comment]
did your jemalloc is used inside ruby check by running this
sudo strace -t readlink ruby -e "42"

**Comment by krzkrzkrz** [comment]
I can check this tomorrow and let you know

**Comment by krzkrzkrz** [comment]
@naveenanilabs Not sure what that is supposed to do

But you also have a typo there, I think. Returns with `-bash: strace: command not found`

**Comment by naveenanilabs** [comment]
worked on ubuntu

**Comment by Pavel077** [comment]
@krzkrzkrz  
Just install strace utility.
In case of ubuntu:  `apt-get install strace`
