### ISSUE TITLE
How to add to PATH?

### ISSUE THREAD

**Issue by krzkrzkrz** [ajgon/opsworks_ruby#176]
What is the recommended way of adding to `PATH`?

Currently in /srv/www/app_name/current/`, I'm having to do `/usr/local/bin/bundle` just to execute commands like:

- `/usr/local/bin/bundle exec rails c staging`
- `/usr/local/bin/bundle exec rake db:migrate --trace`

If `/usr/local/bin` is in `PATH`. I can just do:

- `bundle exec rails c staging`
- `bundle exec rake db:migrate --trace`

Or is there a better approach to this?

**Comment by olbrich** [comment]
which distro are you using?

**Comment by krzkrzkrz** [comment]
@olbrich I am using the Amazon Linux AMI, 2017.09

**Comment by olbrich** [comment]
I'm not sure why that doesn't just work, but it might have something to do with rubygems.  Make sure you update that to the latest as well.  
You may also want to try adding to the path for all users.  I'm not entirely sure how that's done on AWS Linux, but it might involve dropping a file into `/etc/profile.d`

**Comment by krzkrzkrz** [comment]
I manage to get this going by installing the [magic_shell](https://github.com/customink-webops/magic_shell) cookbook

And in `/recipes/setup.rb`:

```
magic_shell_environment 'PATH' do
  value '$PATH:/usr/local/bin'
end
```
