### ISSUE TITLE
Is there a way to restart sidekiq instances?

### ISSUE THREAD

**Issue by krzkrzkrz** [ajgon/opsworks_ruby#177]
When code is pushed, and a deploy is done (i.e. in OpsWorks UI: Deployments -> Deploy an app -> Deploy). Sometimes there is a need to restart Sidekiq instances, so that the workers see the latest code.

I could SSH into each instance and do:

```
sudo su
monit stop sidekiq
monit start sidekiq
```

But that would take a lot of effort, especially if there are several instances running

Wondering to see if I need to create my own recipe for this

**Comment by olbrich** [comment]
After a deploy, the sidekiq handler tells monit to restart the workers.  You really should not have to do anything about this.  Are you having problems with it not reloading properly?

**Comment by krzkrzkrz** [comment]
I can test this out tomorrow. And see if Sidekiq is reloaded on app deploy. I will report back on this thread later during the day, to confirm

**Comment by krzkrzkrz** [comment]
Yeap just tested. Seems like Sidekiq is reloaded after app deploy. 

One small catch. App code is reloaded. But if one changes something in `/initializers/some_file.rb`. Those changes are not reflected/reloaded. Not a big deal, since changes in `/initializers` hardly change. And when they do, the instances normally need a hard reset. i.e. stop and restart.

If this is normal, happy to hear your thoughts on this. Just thought I should point above out

**Comment by krzkrzkrz** [comment]
Closing for now, since original concern has been addressed
