### ISSUE TITLE
Apache2 lbmethod_byrequests causing apache restart to fail 

### ISSUE THREAD

**Issue by zeroedin** [ajgon/opsworks_ruby#179]
Ubuntu 16.04

### Expected Behavior
Apache should restart after the enabling mod lbmethod_byrequests

### Actual Behavior
Apache fails to restart with error below.  

I have been using the same opsworks_ruby recipe for 2 different stacks.  

On one stack which was built 3 days ago Apache is at `Apache/2.4.33` this stack built with no issues.  
This issue I'm reporting started yesterday and I think correlates with the release of `Apache/2.4.34` which is installing on the new stack.  So im not entirely sure that this error has anything to do with opsworks_ruby but adding this issue here in case anyone else runs into this.  

However while debugging I thought that maybe apache modules could be overridable in the node attributes?  Would this be possible?

```Ruby
      def setup
        handle_packages
        enable_modules(%w[expires headers lbmethod_byrequests proxy proxy_balancer proxy_http rewrite ssl])
        install_mod_passenger if passenger?
        add_sites_available_enabled
        define_service(:start)
      end
```
into something like: 

```Ruby
      def setup
        handle_packages
        enable_modules(node['apache2']['enabled_modules'])
        install_mod_passenger if passenger?
        add_sites_available_enabled
        define_service(:start)
      end
```

Or for that matter could the sous-chef apache2 recipe be intergrated instead?  I'm not sure if I understand all the reasons for why it might not be already,  so understood if that is a bag of worms.  

### Custom JSON
Nothing custom

### Chef log including error
```
2018-07-18T15:16:31-04:00] INFO: execute[Enable Apache2 module expires] sending restart action to service[apache2] (delayed)
[2018-07-18T15:16:31-04:00] INFO: Processing service[apache2] action restart (opsworks_ruby::deploy line 39)
 
================================================================================
Error executing action `restart` on resource 'service[apache2]'
================================================================================
 
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /bin/systemctl --system restart apache2 ----
STDOUT: 
STDERR: Job for apache2.service failed because the control process exited with error code. See "systemctl status apache2.service" and "journalctl -xe" for details.
---- End output of /bin/systemctl --system restart apache2 ----
Ran /bin/systemctl --system restart apache2 returned 1
 
Resource Declaration:
---------------------
# In /var/chef/runs/562cd764-94ef-4bb0-b447-0fa38ae27c44/local-mode-cache/cache/cookbooks/opsworks_ruby/libraries/drivers_webserver_base.rb
 
39:         context.service service_name do
40:           supports status: true, restart: true, reload: true
41:           action default_action
42:         end
43:       end
 
Compiled Resource:
------------------
# Declared in /var/chef/runs/562cd764-94ef-4bb0-b447-0fa38ae27c44/local-mode-cache/cache/cookbooks/opsworks_ruby/libraries/drivers_webserver_base.rb:39:in `define_service'
 
service("apache2") do
action [:nothing]
supports {:status=>true, :restart=>true, :reload=>true}
retries 0
retry_delay 2
default_guard_interpreter :default
service_name "apache2"
pattern "apache2"
declared_type :service
cookbook_name "opsworks_ruby"
recipe_name "deploy"
end
 
Platform:
---------
x86_64-linux
```

**Comment by zeroedin** [comment]
It looks like this is an issue module load order that started in 2.4.34

https://serverfault.com/questions/922573/apache2-fails-to-start-after-recent-update-to-2-4-34-no-clue-why

**Comment by ajgon** [comment]
Unfortunately I can't do much about, as it looks like apache/module bug. Hopefully this gets patched soon.

As for configurable modules part - this won't help as well, as all those modules are required by the current [webserver config template](https://github.com/ajgon/opsworks_ruby/blob/6806efa390af57bed3a862946c6560729d061088/templates/default/appserver.apache2.upstream.conf.erb), so removing them (via config JSON) would break the deploy as well.

**Comment by zeroedin** [comment]
Right, but aren't the webserver config templates also configurable and overridable as well via  `app['webserver']['site_config_template_cookbook']` and `app['webserver']['site_config_template']` .  I guess I am assuming that the configurable modules would be an at your own risk sort of thing, with the default attribute set as current?   Again I maybe off base here an missing a link in the chain.

Thanks again for your awesome work on this recipe!

**Comment by zeroedin** [comment]
For the time being, I made the apache modules customizable in my own branch on a fork to get around this apache issue.  I still have not seent he bug documented other the serverfault link above.  If anyone has the URL to the Apache bug itself, please share.

I'm using apache/passenger so the config template issue above doesn't come into play as the passenger template doesn't use lbmethod_byrequest/proxy/proxy_balancer/proxy_http modules.  I would still like to see this customizable in the future since I do not need these modules installed myself, but understand if you don't think it meets muster.

 https://github.com/zeroedin/opsworks_ruby/tree/try-apache-mods-customization
