### ISSUE TITLE
no way to install ruby from source.

### ISSUE THREAD

**Issue by naveenanilabs** [ajgon/opsworks_ruby#181]
there should be  a way to install ruby from source code.
i want to comple ruby with jemalloc but not able to. Is there any way to add jemalloc while installing ruby node.default['ruby-ng']['ruby_version'] = node['ruby-version']
  include_recipe 'ruby-ng::dev'

**Comment by ajgon** [comment]
Installing ruby from source is slightly out of scope of this cookbook. There are probably cookbooks designed just for that - you can use one of these.

If `jemalloc` is the only reason why you need source, check the issue #175 where workaround for that particular problem is discussed.

**Comment by ajgon** [comment]
Or maybe there is a PPA with precomipled ruby binaries with jemalloc? If so, I can add it to supported packages list and add apropriate configuration option.

**Comment by naveenanilabs** [comment]
can we have support for chef_rbenv  it will be great to have rbenv support

**Comment by ajgon** [comment]
Closing this, since [fullstaq repo support have been added](https://github.com/ajgon/opsworks_ruby/commit/13834812966a5ed448a9c637ce1c12c1c06d1143) which should resolve those issues.
