### ISSUE TITLE
Aurora for Postgres isn't an allowed engine

### ISSUE THREAD

**Issue by djgable** [ajgon/opsworks_ruby#182]
### Expected Behavior

Using a registered Aurora Postgres RDS instance with an OpsWorks stack should allow my Rails application to connect to the instance.

### Actual Behavior

When running through the recipe it throws a `There is no supported Db driver for given configuration.`

Following the solve with issue #59, I cloned the repo, added in some temporary logging to determine what the "engine" name is which came back with `aurora-postgresql`.  Not sure if this is the best solution, but as a quick fix I was able to get it working by editing **libraries/drivers_db_postgresql.rb** with the following code:

```
module Drivers
  module Db
    class Postgresql < Base
      adapter :postgresql
      allowed_engines :postgres, :postgresql, 'aurora-postgresql'.to_sym
      packages debian: 'libpq-dev', rhel: 'postgresql96-devel'
    end
  end
end
```

Open to suggestions or thoughts...

**Comment by ajgon** [comment]
I’m perfectly fine with this solution. Thanks! Can you create a pull request with that patch? Also, can you include the engine in the documentation within it?
