### ISSUE TITLE
Apache Configuration Issues

### ISSUE THREAD

**Issue by richseviora** [ajgon/opsworks_ruby#184]
### Expected Behavior

Apache handles static file serving.

### Actual Behavior

Apache 2.4 returns 5xx errors when attempting to serve static assets if Rails is configured not to serve static files.

### Custom JSON

    "deploy": {
        "app_name": {
            "global": {
                "rollback_on_error": false
            },
            "database": {
                "adapter": "postgresql"
            },
            "framework": {
                "migrate": false
            },
            "appserver": {
                "adapter": "unicorn"
            },
            "webserver": {
                "adapter": "apache2",
                "log_level": "trace4"
            }
        }
    }
}

### Observations

There's a few problems with the base Apache site configuration that I've observed, running Apache 2.4 on an Amazon Linux AMI;

#### 1. Missing `Require` statement
The `<Directory>` declaration is using what appears to be Apache 2.2 syntax, causing the server's default(?) 2.4 declaration to take precedence;

```
  <Directory /srv/www/app_name/current>
    Options FollowSymLinks
    AllowOverride None
    Order allow,deny
    Require all granted # This needed to be added.
  </Directory>
```

#### 2. Attempting to Proxy assets;
Unless I disallow proxying for assets, it appears to send all the asset requests onto the Rails server.
```

  # This part still works, and when presented with an asset request it detects that the file still exists and doesn't attempt to rewrite it.
  RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
  RewriteRule ^/(.*)$ balancer://unicorn_app_name%{REQUEST_URI} [P,QSA,L]

  # I had to add this line in order to stop the proxy from rewriting to the URL to include the `balancer://unicorn_app_name` protocol.
  ProxyPass /assets ! 
  ProxyPass / balancer://unicorn_app_name/
  ProxyPassReverse / balancer://unicorn_app_name/
  ProxyPreserveHost on
  ProxyAddHeaders On
  ProxyTimeout 60
```

### Solution

This seems like it's calling for the site configuration template to be revised, but I don't know if we need to support Apache 2.2/earlier?

**Comment by ajgon** [comment]
I basically took the apache template from old chef 11 aws cookbooks, adapted it to opsworks ruby format and never touched it again. Since apache 2.4 is default webserver on both supported stacks (amazon linux and ubuntu) I’m fine with dropping compatibility with 2.2.

Since I’m not an apache expert, can you please create a PR with suggested changes?

Thanks!

**Comment by richseviora** [comment]
I remembered that I had this outstanding, but I see now that these issues have been solved!

**Comment by DuckNG** [comment]
I ran into this same issue recently when trying out opsworks_ruby deploying to an amazon linux instance. Below you will find my current JSON configuration
`{
    "deploy": {
        "app_name": {
            "global": {
                "logrotate_rotate": 14
            },
            "database": {
                "adapter": "postgresql"
            },
            "webserver": {
                "adapter": "apache2"
            },
            "worker": {
                "adapter": "delayed_job",
                "process_count": 1
            }
        }
    },
    "ruby-version": "2.4"
}`

When I tried out the previously proposed changes in this issue everything looked good and apache was able to serve assets from app_name/public. 

I have gone ahead and created a PR with these changes: https://github.com/ajgon/opsworks_ruby/pull/210

In the mean time, If anyone reading this needs a quick fix add the following to your JSON configuration under webserver
`
"extra_config": "  <Location \"/assets/\">\n    ProxyPass \"!\"\n  </Location>\n\n  <Directory /srv/www/app_name/current>\n    Require all granted\n  </Directory>"
`
