### ISSUE TITLE
No candidate version available for ruby25 on Amazon Linux 2017.09

### ISSUE THREAD

**Issue by Geniekort** [ajgon/opsworks_ruby#187]
I'm trying to set up aws opsworks with a ruby application, however, when using the opsworks_ruby cookbook, on setup, chef throws an error. It seems that the package for ruby can not be found. 
At first I did not specify any ruby version in the custom JSON, but adding it does not make any difference. It still throws the error for ruby25. 

### Expected Behavior
The setup command in opsworks finished.

### Actual Behavior
The setup command in opsworks throws an error.

### Custom JSON
**Only used to debug, adding or removing this doesn't make any difference**
```json
{
    "deploy": {
        "*appname*": {
            "global": {
                "ruby-version": "2.4"
            }
        }
    }
}
```

### Chef log including error
```
================================================================================
Error executing action `install` on resource 'yum_package[ruby25]'
================================================================================
 
Chef::Exceptions::Package
-------------------------
No candidate version available for ruby25
 
Resource Declaration:
---------------------
# In /var/chef/runs/9641ec98-0245-4b5d-9804-a13a3dabea8b/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/setup.rb
 
51:   package "ruby#{ruby_pkg_version.join('')}"
52:   package "ruby#{ruby_pkg_version.join('')}-devel"
 
Compiled Resource:
------------------
# Declared in /var/chef/runs/9641ec98-0245-4b5d-9804-a13a3dabea8b/local-mode-cache/cache/cookbooks/opsworks_ruby/recipes/setup.rb:51:in `from_file'
 
yum_package("ruby25") do
package_name "ruby25"
action [:install]
retries 0
retry_delay 2
default_guard_interpreter :default
declared_type :package
cookbook_name "opsworks_ruby"
recipe_name "setup"
flush_cache {:before=>false, :after=>false}
end


```

**Comment by ajgon** [comment]
Hey, it's a bug in generator, as [omenking found out](https://github.com/ajgon/opsworks_ruby/issues/190). You should use `ruby-version` outside of `deploy` block i.e.:

```json
{
 "ruby-version": "2.4",
  "deploy": {
    "app": {
      ...
    }
  }
}
```

I'll fix the generator soon, sorry for the confusion!
