### ISSUE TITLE
How to customize nginx conf?

### ISSUE THREAD

**Issue by krzkrzkrz** [ajgon/opsworks_ruby#189]
At `opsworks_ruby/templates/default/appserver.nginx.conf.erb`, I have the following:

1) Ability for the load balancer to perform health checks:

```
location /ping {
  access_log off;
  return 200;
}
```

2) My load balancer uses the SSL certificate to terminate the connection and then decrypt requests from clients before sending them to the instances (also known as SSL termination). 

Further details at https://aws.amazon.com/blogs/aws/elastic-load-balancer-support-for-ssl-termination/

Which also means, anyone landing on the following domains, should be redirected to the https protocol. For example:

- http://www.domain-name.com to https://www.domain-name.com

To achieve this. I have:

```
server {
  listen <%= @out[:port] %>; # Typically listens on port 80
  ...
  location @<%= @name %> {
    ...
    # Any request that did not originally come in to the ELB over HTTPS gets redirected
    if ($http_x_forwarded_proto != "https") {
      rewrite ^(.*)$ https://$server_name$1 permanent;
    }
    ...
  }
  ...
}
```

3) To redirect the bare domain names to the https counterpart, i.e:

- http://domain-name.com to https://www.domain-name.com
- https://domain-name.com to https://www.domain-name.com

I have the following:

```
# If request is made to the bare domain (i.e. domain-name.com)
# Issue a redirect 301 response
server {
  listen 80;
  server_name domain-name.com;

  location /ping {
    access_log off;
    return 200;
  }

  location / {
    return 301 https://www.$server_name$request_uri;

    # Add HTTP Strict Transport Security for good measure
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains;";
  }
}
```

All seems to work so far. However, what I had to do, was fork this repo, and manually edit `appserver.nginx.conf.erb` to include all 3 definitions above. And then have my `Berkfile` install the cookbook from the forked version. i.e. `cookbook 'opsworks_ruby', :git => 'https://github.com/git-user-name/opsworks_ruby.git'`

Wondering if there is a more dynamic way of including these definition so I wouldnt have to fork

**Comment by ajgon** [comment]
This is a good approach. The goal of this cookbook, is to provide most common, out-of-the box configuration set. However if requirements are more specific (like in this case) - it should be customisable by manual forking and editing necessary configuration files. 

So if this solution works for you - go for it! 👍 

The open question is - should we add a support of this to `opsworks_ruby`. I think, force-redirect http to https is a good approach and should be at least available as a configuration option. I'll keep this ticket open for now, and implement it as soon as I can.

Thank you!

**Comment by olbrich** [comment]
It seems like a pretty common use case to force a redirect from http -> https.  I'd like to see support for it.
