### ISSUE TITLE
Ruby version remains the same after upgrade

### ISSUE THREAD

**Issue by willkoehler** [ajgon/opsworks_ruby#199]
This only happens in the Debian platform family - Ubuntu 16.04 specifically in my case.

### Steps to Reproduce

* Launch an instance on Ruby 2.3
```json
{
    "ruby-version": "2.3"
}
```

* Change the Ruby version in the Stack JSON to 2.5
```json
{
    "ruby-version": "2.5"
}
```

* Run Setup on the Stack
* Ruby 2.5 package is installed. Ruby 2.3 package remains installed.
```
ubuntu@rails1:~$ apt list --installed | grep ruby

libruby2.3/xenial,now 2.3.8-4bbox1~xenial1 amd64 [installed,automatic]
libruby2.5/xenial,now 2.5.3-1bbox1~xenial1 amd64 [installed,automatic]
opsworks-agent-ruby/now 2.2.3-1 amd64 [installed,local]
ruby2.3/xenial,now 2.3.8-4bbox1~xenial1 amd64 [installed]
ruby2.3-dev/xenial,now 2.3.8-4bbox1~xenial1 amd64 [installed]
ruby2.5/xenial,now 2.5.3-1bbox1~xenial1 amd64 [installed]
ruby2.5-dev/xenial,now 2.5.3-1bbox1~xenial1 amd64 [installed]
ruby2.5-doc/xenial,now 2.5.3-1bbox1~xenial1 all [installed,automatic]
rubygems-integration/xenial,now 1.10 all [installed,automatic]
```

* Alternatives still points to Ruby 2.3, so current version of Ruby is still 2.3
```
ubuntu@rails1:~$ ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux-gnu]
ubuntu@rails1:~$ which ruby
/usr/bin/ruby
ubuntu@rails1:~$ ls -lh /usr/bin/ruby
lrwxrwxrwx 1 root root 22 Dec 17 21:54 /usr/bin/ruby -> /etc/alternatives/ruby
ubuntu@rails1:~$ ls -lh /etc/alternatives/ruby
lrwxrwxrwx 1 root root 16 Dec 17 21:54 /etc/alternatives/ruby -> /usr/bin/ruby2.3
```

**Comment by willkoehler** [comment]
It's easy to fix on a single instance by manually uninstalling the old version of Ruby.

```
ubuntu@rails1:~$ sudo apt-get remove ruby2.3
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  ruby2.3
0 upgraded, 0 newly installed, 1 to remove and 2 not upgraded.
After this operation, 94.2 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 127616 files and directories currently installed.)
Removing ruby2.3 (2.3.8-4bbox1~xenial1) ...
update-alternatives: using /usr/bin/gem2.5 to provide /usr/bin/gem (gem) in auto mode
update-alternatives: using /usr/bin/ruby2.5 to provide /usr/bin/ruby (ruby) in auto mode
Processing triggers for man-db (2.7.5-1) ...
ubuntu@rails1:~$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]
```

But there doesn't appear to be a way to automate this upgrade.

**Comment by olbrich** [comment]
AFAIK the ruby packaging part will not upgrade the version, but will just detect that ruby is installed and move on, regardless of the version.

If you build a new instance from scratch, it should come up with the new ruby version.   This has the bonus side effect of installing all the recent OS security patches.  I personally favor building new instances on a regular basis as it has security benefits and it forces you to exercise the `setup` part of your cookbooks regularly. 

If you want the deploy to fail when the ruby version isn't correct, add a ruby version specifier to your Gemfile and the bundle install phase will fail if the correct version is not on the instance.

**Comment by ajgon** [comment]
The idea is, that `setup` recipe should be used only once, when instance is brang to life. If something changes, and `setup` needs to be performed again, the new instance should be fired up, and old one put down.
