### ISSUE TITLE
Install ruby via. official snap package

### ISSUE THREAD

**Issue by olbrich** [ajgon/opsworks_ruby#200]
Feature request:  Use official snap package to install ruby

https://www.ruby-lang.org/en/news/2018/11/08/snap/

In theory this should work for any distro.

**Comment by ajgon** [comment]
Closing this in favor of [fullstaq implementation](https://github.com/ajgon/opsworks_ruby/commit/13834812966a5ed448a9c637ce1c12c1c06d1143).
