### ISSUE TITLE
install ruby using rvm or rbenv

### ISSUE THREAD

**Issue by naveenanilabs** [ajgon/opsworks_ruby#202]
there should be a way to install ruby using rbenv or rvm

**Comment by ajgon** [comment]
I'm not sure, why?. If you need a different version, you can always spin up a new instance with it. What's the point of having multiple ruby versions on one instance?

**Comment by naveenanilabs** [comment]
i want to compile ruby with jemalloc which can be easily done with rbenv or rvm, and we don't have to depend on platform for ruby versions.

**Comment by inopinatus** [comment]
Very interested in https://fullstaqruby.org/ for this in future. Comes from the creator of Passenger.

**Comment by inopinatus** [comment]
Note that on Ubuntu you can use jemalloc with the Brightbox binaries right now. I install the `libjemalloc1` package, then set LD_PRELOAD in my OpsWorks application environment variables to `/usr/lib/x86_64-linux-gnu/libjemalloc.so.1`.

**Comment by ajgon** [comment]
Looks like, fullstaqruby provides debian packages - it's worth considering replacing brightbox with it. 

I'm closing this ticket, as workaround for jmalloc can be provided without rbenv/rvm.
