### ISSUE TITLE
Nginx cookbook - minimun Chef version

### ISSUE THREAD

**Issue by djgable** [ajgon/opsworks_ruby#222]
The nginx cookbook is expecting a minimum chef version of 14. As far as I know its only possible to have up to ~>12 with OpsWorks. This seems to be with respect to a new version of the nginx cookbook released last month (10.0.1). 

### Expected Behavior
Upgrading from 1.14.0 to 1.15.0, expecting a successful deployment.

### Actual Behavior
deployment / updates fail. Error message states that the minimum nginx version is not met.

### Chef log including error
```
[2019-09-04T17:50:03+00:00] ERROR: Cookbook 'nginx' version '10.0.1' depends on chef version [">= 14"], but the running chef version is 12.18.31
[2019-09-04T17:50:03+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by djgable** [comment]
Actually, in troubleshooting further, noticed a similar issue with the Ohai cookbook as well. They just released a version update about 6 days ago with a new minimum Chef version.

**Comment by aka47** [comment]
Adding cookbook 'nginx', '8.1.6' to the Berksfile fixes it for now.. also had to add cookbook 'ohai', '5.2.5'

```
cookbook 'nginx', '8.1.6'
cookbook 'ohai', '5.2.5'
```

**Comment by djgable** [comment]
Yeah @aka47, I did the same thing and it worked. I believe the only thing that differed from your code is that I used nginx ver 9.0.0.

**Comment by inopinatus** [comment]
I went with `depends 'nginx', '<9.0.0'` because there was something off about the 9.0.0 release.
