### ISSUE TITLE
Yarn in before_migrate fails -- seems like it runs as root

### ISSUE THREAD

**Issue by aka47** [ajgon/opsworks_ruby#223]
### Expected Behavior
yarn should run in before_symlink.rb webhook
This bug seems like a chef bug somehow, it happens in chef 12 but also in the latest chef 14 version ..

### Actual Behavior
it fails with 
yarn install v1.17.3
error An unexpected error occurred: "EACCES: permission denied, scandir '/root/.config/yarn/link'".

### the before hook

```
bash 'yarn' do
    ignore_failure true # until fixed
    user 'deploy'
    cwd  release_path
    environment 'NODE_ENV': 'production'
    code <<-EOH
      yarn
    EOH
  end
```

### Chef log including error
[2019-09-11T17:35:19+00:00] WARN: deploy/before_symlink.rb
[2019-09-11T17:35:19+00:00] WARN: precompile assets and running yarn and webpack.js -p
[2019-09-11T17:35:19+00:00] WARN: deploy/before_symlink.rb END
 
* execute[rake assets:precompile] action run[2019-09-11T17:35:19+00:00] INFO: Processing execute[rake assets:precompile] action run (/srv/www/jovoto_test_app/releases/20190911173441/deploy/before_symlink.rb line 22)
 
[execute] `/root` is not writable.
Bundler will use `/tmp/bundler/home/root' as your home directory temporarily.
WARNING: Skipping key "RAILS_ENV". Already set in ENV.
WARNING: Skipping key "HOME". Already set in ENV.
WARNING: Skipping key "USER". Already set in ENV.
yarn install v1.17.3
error An unexpected error occurred: "EACCES: permission denied, scandir '/root/.config/yarn/link'".
info If you think this is a bug, please open a bug report with the information provided in "/srv/www/jovoto_test_app/releases/20190911173441/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

## my current workaround
run yarn inside sudo su deploy -c. 
 
```
execute 'yarrnnn & webpack' do
  cwd  release_path
  environment 'NODE_ENV': 'production', 'YARN_CACHE_FOLDER': 'tmp/cache/'
  command "sudo su deploy -c 'yarn && node node_modules/webpack/bin/webpack.js -p'"
end
```

**Comment by ajgon** [comment]
I'm closing this one, as I think this workaround is a proper way to do this. It looks like yarn problem, not chef/opsworks itself.

I'm not a JS dev, but doesn't yarn have some ENV variable for `.config/yarn` forlder? If so, it should be changed to `tmp/yarn` or whatever and then it can be ran without `su -c deploy` workaround.
