### ISSUE TITLE
Recent upgrade to sudo and ark cookbooks are not compatible with OpsWorks Chef (v12.18.31)

### ISSUE THREAD

**Issue by willkoehler** [ajgon/opsworks_ruby#230]
The most recent versions of the sudo cookbook (https://supermarket.chef.io/cookbooks/sudo/) and ark cookbook (https://supermarket.chef.io/cookbooks/ark) require a newer version of chef then comes on OpsWorks instances.

I had to lock these cookbooks to older versions to get opsworks_ruby to work again after I updated everything.

I added these to my `Berksfile`

```
cookbook 'sudo', '= 5.4.4'        # lock to 5.4.4 for compatibility with chef < 12.21.3
cookbook 'ark', '= 4.0.0'         # lock to 4.0.0 for compatibility with chef < 14
```

The new `node['chef-version']` is a great addition, but unfortunately doesn't help in this case because opsworks_ruby never gets a chance to run because of the version requirements. I see messages like `Cookbook 'ark' version '5.0.0' depends on chef version [">= 14.0"], but the running chef version is 12.18.31` in the logs. Locking cookbooks to older versions is the only fix.

**Comment by ajgon** [comment]
I froze the versions you suggested in cookbook `metadata.rb` file. 

Unfortunately there is no easy way to update them after chef version upgrade, so even with new chef version, user is still stuck with old cookbooks unless he updates them manually.

But this is a great catch - thank you!
