### ISSUE TITLE
How do you do daily log rotates, but also by size?

### ISSUE THREAD

**Issue by krzkrzkrz** [ajgon/opsworks_ruby#234]
Right now, I am setting `logrotate_rotate` to `15`, `logrotate_frequency` to `daily`. It rotates the log up to 15 days, which is expected.

However, I am noticing some logs are taking up to 500MB++, which in time, can fill up the disk space (8gb usually). How do I limit each log file to say, `50mb`?

**Comment by ajgon** [comment]
It's not documented feature, but you can actually use any logrotate config file property with `logrotate_` prefix as an config option and it should work.

So in that case `logrotate_size 50m` should do the trick.
