### ISSUE TITLE
How does one determine what thread_max is currently set to?

### ISSUE THREAD

**Issue by krzkrzkrz** [ajgon/opsworks_ruby#235]
Currently I am doing

```
ps aux | grep puma
ps -h -o nlwp 7498
```

`7498` is the actual pid Puma is running on.

Reason why I am asking. I want to verify that `thread_max` is currently being set correctly?

Right now I have:

```
            "appserver": {
                "dot_env": true,
                "worker_processes": 3,
                "thread_max": 5
            },
```
But have a feeling that, the thread count configured for Puma is still set to the default (`16`)

**Comment by ajgon** [comment]
Puma runs with config from `shared` folder which should be generated by `opsworks_ruby`. 

https://github.com/ajgon/opsworks_ruby/blob/master/libraries/drivers_appserver_puma.rb#L17

Can you check `/srv/www/app_name/shared/config/puma.rb` and checks `threads` there?
