### ISSUE TITLE
Failure to add fullstaq ruby to my OpsWorks Stacks hosted application

### ISSUE THREAD

**Issue by mileslane** [ajgon/opsworks_ruby#236]
### Expected Behavior

I have updated opsworks_ruby to 0.18.0 and have added the fullstaq configuration settings to my application's cookbook attributes/default.rb. I expected the fullstaq ruby repository to be added and the fullstaq ruby to be installed on my application's  OpsWorks stack.

### Actual Behavior

Hit:9 https://download.newrelic.com/infrastructure_agent/linux/apt xenial InRelease
Ign:11 https://apt.fullstaqruby.org ubuntu-16.04 InRelease
Ign:12 https://apt.fullstaqruby.org ubuntu-16.04 Release
Ign:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Ign:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Ign:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Ign:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Ign:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Err:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
404  Not Found
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Reading package lists...
STDERR: W: The repository 'https://apt.fullstaqruby.org ubuntu-16.04 Release' does not have a Release file.
E: Failed to fetch https://apt.fullstaqruby.org/dists/ubuntu-16.04/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

### Custom JSON
```json
node.default['ruby-provider'] = 'fullstaq'
node.default['ruby-variant'] = 'jemalloc'
node.default['ruby-version'] = '2.6'
```

**Comment by ajgon** [comment]
Hey.

Unfortunatelly fullstaq [doesn't provide](https://dl.bintray.com/fullstaq/fullstaq-ruby-apt/dists/) packages for Ubuntu 16.04. You need to update your distro to 18.04.
