### ISSUE TITLE
Are you interested in a PR to use Lets Encrypt?

### ISSUE THREAD

**Issue by willkoehler** [ajgon/opsworks_ruby#239]
I recently added Lets Encrypt (via certbot https://certbot.eff.org) to one of my opsworks_ruby-managed deployments. It was surprisingly easy. See https://github.com/willkoehler/opsworks-rails/tree/master/letsencrypt.

What I did was specific to my configuration. But it should be straightforward to generalize since certbot does most of the work.

Would you be interested in a PR to incorporate this into opsworks_ruby? TBH your familiarity with opsworks_ruby might make it easier to do it yourself vs talking me through all the config, but I'm happy to give it a shot.

**Comment by ajgon** [comment]
Hey!

As much as I love the idea, I'm not sure if it's a proper use case for this cookbook. The core principle of `opsworks_ruby` was always to mimic old Chef11 stack of long gone "full version" of OpsWorks. We've moved away from this path some time ago, but still trying to keep this in mind.

All the other stuff, should be a responsibility of other chef cookbooks - which is exactly what you did - wrote separate cookbook to solve the problem.

So, to conclude, I leave this decision up to you. If you like to add this functionality to this cookbook, I'll be perfectly happy, to review it (fix if necessary) and merge it (with full creditability to you of course).

Anyway - great work. I was suprised, that adding LE cert was that simple :)

**Comment by willkoehler** [comment]
Cool 😄 That makes sense. I think we should hold off for now.

I'm happy to revisit if it ever becomes a priority. But I understand your philosophy that this is not core functionality that belongs in opsworks_rails.
