### ISSUE TITLE
Cookbook not compatible with default opsworks chef 12 

### ISSUE THREAD

**Issue by cratz** [ajgon/opsworks_ruby#242]
### Expected Behavior
Cookbook is compatible with chef  12 (used by OpsWorks)

### Actual Behavior
`deploy_resource` cookbook requires chef >= 13.0
Using `chef-version` will not help since it already fails on checking `metadata.rb`

### Custom JSON
```json
{
  "chef-version": 16
}
```

### Chef log including error

ERROR: Cookbook 'deploy_resource' version '1.0.3' depends on chef version [">= 13.0"], but the running chef version is 12.18.31

**Comment by aka47** [comment]
I ran into the same problem a week ago, suddenly starting new instances does not work anymore. Until now I did not find a way to mitigate this problem or workaround it. 
ANY HELP or ideas would be so great - it kills the whole deployment and break setup of our rails-instances.

**Comment by ajgon** [comment]
I created a new branch which should do the trick: [fix/include-deploy-resource](https://github.com/ajgon/opsworks_ruby/tree/fix/include-deploy-resource). Can you please take a look if it works for you? I tested it both with Chef 12 and 14 and looks like it's working.

**Comment by aka47** [comment]
I tested it and it fixes the problem, yes. Thanks a lot @ajgon for your quick response.

**Comment by cratz** [comment]
@ajgon Thanks a lot for the fix. Maybe I will give it a try later again.
