### ISSUE TITLE
Monit restart fails to load generated monitrc for unicorn

### ISSUE THREAD

**Issue by rkenzhebekov** [ajgon/opsworks_ruby#253]
### Expected Behavior
OS: Ubuntu 16 LTS

Cookbooks:
cookbook 'monit-ng', '2.4.0'
cookbook 'opsworks_ruby', '1.20.2'

When monitrc files are generated for appserver or worker it should be generated with file extension *.conf. So that monit can load service names properly.

### Actual Behavior

Currently, appserver and worker files generated with *.monitrc extension in /etc/monit/conf.d/ directory. When `monit restart example_unicorn_name` command is triggered as part of deploy it is unable to restart monitrc files since /etc/monit/monitrc file is generated with this code at the bottom:

```
include /etc/monit/conf.d/*.conf
```

### Chef log including error
```
/etc/monit/monitrc:32: Include failed -- Success '/etc/monit/conf.d/*.conf'
There is no service named "example_unicorn_name"
```

I'm not sure if this issue belong to monit-ng template file or to opsworks_ruby.

**Comment by ajgon** [comment]
Unfortunatelly it's hardcoded in `monit-ng` - https://github.com/bbg-cookbooks/monit-ng/blob/master/templates/default/monit.conf.erb#L75 .

To make this work with `opsworks_ruby` you probably need some recipe to symlink the files, or alter either `monit-ng` to include `*.monitrc` files, or `opsworks_ruby` to generate `*.conf`. Good luck :)
