### ISSUE TITLE
insecure by default: apache server-status is exposed

### ISSUE THREAD

**Issue by michaelglass** [ajgon/opsworks_ruby#259]
### Expected Behavior
`my-website.com/server-status` yields a 404

### Actual Behavior
`my-website.com/server-status` shows private sever stats

I believe we need to explicitly `a2dismod status`

thank you for your cookbooks!

**Comment by ajgon** [comment]
Fix was applied in `1.20.3` version. By default `mod_status` is enabled, to maintain backwards compatibility. To disable it, you need to add to your application JSON:

```json
{
  "deploy": {
    "my_application_name": {
      "webserver": {
        "adapter": "apache2",
        "enable_status": false
      }
    }
  }
}
```

Thanks for the report!
