### ISSUE TITLE
Setup/configure constantly rerunning after upgrading to Ubuntu 18.04/OpsWorks agent 4040. Also unable to upload chef.logs to s3. 

### ISSUE THREAD

**Issue by jhirn** [ajgon/opsworks_ruby#291]
Hello. We've had an Opsworks stack running on an extremely dated fork which was recently hard reset to `ajgon/opsworks` main. There are only a small number of patches on top of trunk, changes to the update (adding hutch worker support and a method to install additional packages). The cookbook seems to be ok. All of the recipes run without issue and it was in a testing environment for a few weeks without issue. However upon moving to the QA/Staging environments, we're getting an odd reboot loop which is rerunning configure and sometimes deploy+configure steps for a reason I can't determine. 

Another side effect of this is the opsworks agent is unable to upload the deploy logs. I don't believe this to be related to the cookbook at all but it's making troubleshooting less fun so tossing it out there in case anyone else gets the same. I'm seeing an error 127 code in the opsworks agent log trying to upload the gzip file but no dice. 

The app is a pretty basic 3 layer stack, application (puma)/sidekiq-pro, hutch (rabbitmq). It seems the sidekiq servers like to re-run deploy more often while the Rails app is simply running configure. I can't seem to even determine why this might be happening so even pointing me to some agent/sys logs would be a major help. There were not any changes to the stack other than : 

* upgrading the instance type (t2.medium -> t3.medium/t3a.medium), 
* Opsworks agent (4022 -> Have tried 4033, 4040)
* OS ( Ubuntu 16.04 -> 18.04)

All instances were created new and the old ones deleted. Nothing stands out in the `/var/chef/runs/XXX/chef.log` files. I've double checked folder permissions against yet-to-be upgraded stacks. Can't find anything. We've opened a ticket with AWS regarding the logs but hoping the Ruby community may come through like it always does. =)

### Expected Behavior
Configure and Setup are only run once or explicitly. 

### Actual Behavior
![Untitled2](https://user-images.githubusercontent.com/167089/193847029-207e1d6e-a413-4752-9ea8-b7cecd39f9aa.png)

![Untitled2](https://user-images.githubusercontent.com/167089/193847044-2b7a1bb2-401c-406c-8ebc-b64136448fa4.png)

### Custom JSON
```json
//Stack
{
    "ruby-version": "3.1.2",
    "ruby-provider": "fullstaq",
    "ruby-variant": "jemalloc",
    "additional_packages": [
        "libcurl3",
        "libcurl3-gnutls",
        "libcurl4-openssl-dev",
        "zlib1g-dev",
        "liblzma-dev",
        "imagemagick"
    ]
}
//Application Layer
{
    "deploy": {
        "core_api": {
            "framework": {
                "assets_precompile": false
            },
            "appserver": {
                "application_yml": true,
                "timeout": 120,
                "on_worker_boot": "LaunchDarklyClient.init",
                "worker_processes": 3,
                "thread_min": 16,
                "thread_max": 16
            },
            "database": {
                "pool": 48
            },
            "webserver": {
                "_extra_config_comment": "Redirect HTTP Requests to HTTPS, unless it is the /health_check endpoint. (extraneous spacing preserves nginx conf file formatting)",
                "extra_config": "set $redirect_to_https 0;\n  if ($http_x_forwarded_proto != 'https') { set $redirect_to_https 1; }\n  if ($request_uri = '/health_check') { set $redirect_to_https 0; }\n  if ($redirect_to_https = 1) { return 301 https://$host$request_uri; }",
                "client_max_body_size": "30m",
                "proxy_read_timeout": 120
            }
        }
    }
}
//Hutch Layer 
// (custom driver extending  Drivers::Worker:Base with add/restart/unminotor monit and a hutch.monitrc.erb that worked fine prior to upgrade. 
{
    "deploy": {
        "core_api": {
            "framework": {
                "assets_precompile": false
            },
            "appserver": {
                "adapter": null,
                "application_yml": true
            },
            "webserver": {
                "adapter": null
            },
            "worker": {
                "adapter": "hutch"
            }
        }
    }
}
// Sidekiq 
{
    "deploy": {
        "core_api": {
            "framework": {
                "assets_precompile": false
            },
            "appserver": {
                "adapter": null,
                "application_yml": true
            },
            "webserver": {
                "adapter": null
            },
            "worker": {
                "adapter": "sidekiq",
                "config": {
                    "verbose": true,
                    "logfile": "./log/sidekiq.log",
                    "concurrency": 5,
                    "queues": [
                        "default",
                        "email",
                        "integrations_api",
                        "mailers",
                        "project",
                        "product",
                        "document",
                        "smart_parser.pdf.images",
                        "smart_parser.pdf.json",
                        "smart_parser.pdf.text",
                        "smart_parser.pdf.compress",
                        "action_mailbox_routing",
                        "active_storage_analysis",
                        "action_mailbox_incineration",
                        "active_storage_purge"
                    ]
                }
            }
        }
    }
}
```

### Chef log including error

No errors other than 404 connecting to ChefZero. Happy to learn if there's a way to get more verbose logs. I really just need to figure out what's triggering the setup/configure.

**Comment by l33z3r** [comment]
I am having a similar issue. The sidekiq instances are running OOM because monit keeps starting new instances of sidekiq. It somehow cannot detect that it has successfully started a sidekiq instance and then it continues to start more instances. If you run `monit status` you will see that it is failing, however the processes are actually being created.
