### ISSUE TITLE
Sidekiq goes quiet after deploy

### ISSUE THREAD

**Issue by Maxoos** [ajgon/opsworks_ruby#292]
### Expected Behavior
When deploying a new version the workers should restart and continue working

### Actual Behavior
When deploying a new version the workers go quiet and require a manual restart. I am unsure if monit restarts the workers or not, but they stop processing new jobs and "quiet" label is showing: 
<img width="54" alt="image" src="https://user-images.githubusercontent.com/1913291/196913311-18779279-d276-4f7e-a204-0659390285c4.png">

### Custom JSON
```json
{
    "deploy": {
        "cubbi": {
            "global": {
                "environment": "staging"
            },
            "framework": {
                "assets_precompile": false
            },
            "worker": {
                "adapter": "sidekiq",
                "process_count": 1,
                "config": {
                    "verbose": true,
                    "concurrency": 4,
                    "queues": [
                        "mailers",
                        "critical",
                        "default",
                        "uploader",
                        "low"
                    ],
                    "staging": {
                    },
                    "production": {
                    },
                    "development": {
                        "verbose": true,
                        "concurrency": 2,
                        "pool": 12
                    }
                }
            }
        }
    }
}
```

**Comment by ajgon** [comment]
It's hard to tell what's going on... `opsworks_ruby` should restart all monit hooks after deploy as stated here: https://github.com/ajgon/opsworks_ruby/blob/master/libraries/drivers_worker_sidekiq.rb#L22 . Hook itself is handled here: https://github.com/ajgon/opsworks_ruby/blob/d5975f58334adb9a0834951be54fe8a36a257c86/libraries/helpers.rb#L56-L67 . 

Can you add some debugging/puts statements there and see if the command is actually fired and with what parameters?
