### ISSUE TITLE
Problems with webserver = null

### ISSUE THREAD

**Issue by jagthedrummer** [ajgon/opsworks_ruby#30]
I'm trying to disable unicorn and nginx entirely. I've been successful at disabling unicorn by using

```ruby
default['deploy']['report_convertor']['appserver']['adapter'] = 'null' # Don't run unicorn
```

but when I try to use

```ruby
default['deploy']['report_convertor']['webserver']['adapter'] = 'null' # Don't run nginx
```

I get the error below during the 'configure' step.

Seeing that it's ssl related I tried adding these two lines as well, but it didn't help.

```ruby
default['deploy']['report_convertor']['webserver']['extra_config_ssl'] = false
default['deploy']['report_convertor']['webserver']['ssl_for_legacy_browsers'] = false 
```

Here's the bits of the log around the error:

```
[2016-08-25T19:41:10+00:00] INFO: template[/srv/www/report_convertor/shared/config/unicorn.conf] created file /srv/www/report_convertor/shared/config/unicorn.conf
[2016-08-25T19:41:10+00:00] INFO: template[/srv/www/report_convertor/shared/config/unicorn.conf] updated file contents /srv/www/report_convertor/shared/config/unicorn.conf
[2016-08-25T19:41:10+00:00] INFO: template[/srv/www/report_convertor/shared/config/unicorn.conf] owner changed to 5000
[2016-08-25T19:41:10+00:00] INFO: template[/srv/www/report_convertor/shared/config/unicorn.conf] group changed to 33
[2016-08-25T19:41:10+00:00] INFO: template[/srv/www/report_convertor/shared/config/unicorn.conf] mode changed to 644
[2016-08-25T19:41:10+00:00] INFO: Processing template[/srv/www/report_convertor/shared/scripts/unicorn.service] action create (opsworks_ruby::configure line 53)
[2016-08-25T19:41:10+00:00] INFO: template[/srv/www/report_convertor/shared/scripts/unicorn.service] created file /srv/www/report_convertor/shared/scripts/unicorn.service
[2016-08-25T19:41:10+00:00] INFO: template[/srv/www/report_convertor/shared/scripts/unicorn.service] updated file contents /srv/www/report_convertor/shared/scripts/unicorn.service
[2016-08-25T19:41:10+00:00] INFO: template[/srv/www/report_convertor/shared/scripts/unicorn.service] owner changed to 5000
[2016-08-25T19:41:10+00:00] INFO: template[/srv/www/report_convertor/shared/scripts/unicorn.service] group changed to 33
[2016-08-25T19:41:10+00:00] INFO: template[/srv/www/report_convertor/shared/scripts/unicorn.service] mode changed to 755
[2016-08-25T19:41:10+00:00] INFO: Processing service[unicorn_report_convertor] action nothing (opsworks_ruby::configure line 65)
[2016-08-25T19:41:10+00:00] INFO: Processing directory[/etc/nginx/ssl] action create (opsworks_ruby::configure line 56)
 
================================================================================
Error executing action `create` on resource 'directory[/etc/nginx/ssl]'
================================================================================
 
Chef::Exceptions::EnclosingDirectoryDoesNotExist
------------------------------------------------
Parent directory /etc/nginx does not exist, cannot create /etc/nginx/ssl
 
Cookbook Trace:
---------------
/var/chef/runs/d90bb86d-c81d-4636-9497-fe1e82d6a77a/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
 
Resource Declaration:
---------------------
# In /var/chef/runs/d90bb86d-c81d-4636-9497-fe1e82d6a77a/local-mode-cache/cache/cookbooks/opsworks_ruby/libraries/drivers_webserver_nginx.rb
 
56:         context.directory '/etc/nginx/ssl' do
57:           owner 'root'
58:           group 'root'
59:           mode '0700'
60:         end
61:       end
 
Compiled Resource:
------------------
# Declared in /var/chef/runs/d90bb86d-c81d-4636-9497-fe1e82d6a77a/local-mode-cache/cache/cookbooks/opsworks_ruby/libraries/drivers_webserver_nginx.rb:56:in `add_ssl_directory'
 
directory("/etc/nginx/ssl") do
action [:create]
retries 0
retry_delay 2
default_guard_interpreter :default
path "/etc/nginx/ssl"
declared_type :directory
cookbook_name "opsworks_ruby"
recipe_name "configure"
mode "0700"
owner "root"
group "root"
end
 
Platform:
---------
x86_64-linux
 
[2016-08-25T19:41:10+00:00] INFO: Running queued delayed notifications before re-raising exception
[2016-08-25T19:41:10+00:00] ERROR: Running exception handlers
[2016-08-25T19:41:10+00:00] ERROR: Exception handlers complete
[2016-08-25T19:41:10+00:00] FATAL: Stacktrace dumped to /var/chef/runs/d90bb86d-c81d-4636-9497-fe1e82d6a77a/local-mode-cache/cache/chef-stacktrace.out
[2016-08-25T19:41:10+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-08-25T19:41:10+00:00] ERROR: directory[/etc/nginx/ssl] (opsworks_ruby::configure line 56) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /etc/nginx does not exist, cannot create /etc/nginx/ssl
[2016-08-25T19:41:11+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by jagthedrummer** [comment]
I've been able to get the 'configure' step to work with the config lines mentioned above by also adding this to a recipe that runs before opsworks_ruby.

```ruby
directory '/etc/nginx' do
  owner 'root'
  group 'root'
  mode '0755'
  action :create
end

directory '/etc/nginx/sites-available' do
  owner 'root'
  group 'root'
  mode '0755'
  action :create
end

directory '/etc/nginx/sites-enabled' do
  owner 'root'
  group 'root'
  mode '0755'
  action :create
end
```

**Comment by phongsi** [comment]
Hey @jagthedrummer, if you have enabled the 'null' webserver, it shouldn't be doing anything with nginx.

On configure it will build the null webserver https://github.com/ajgon/opsworks_ruby/blob/master/recipes/configure.rb#L28
then it will fire the hook for configure on the null webserver https://github.com/ajgon/opsworks_ruby/blob/master/recipes/configure.rb#L30

But the configure that runs should just return because its inherited and not defined by the null webserver. https://github.com/ajgon/opsworks_ruby/blob/master/libraries/drivers_base.rb#L26

Does this make sense. 

In you're scenario it looks like it ran the default which is https://github.com/ajgon/opsworks_ruby/blob/master/libraries/drivers_webserver_factory.rb#L15.

Perhaps double check the app shortname for your instance. Also try logging out the engine class to make sure it definitely is the Null webserver. You shouldnt need to do anything besides specifying a null webserver.

Let me know if this helps and also what you find.

**Comment by jagthedrummer** [comment]
Hey @phongsi, I'm sure that my application short name is correct because I'm using the same short name to disable unicorn and that works as expected, with no side effects. And it actually seems like disabling nginx _mostly_ works, it just fails around SSL stuff since it's trying to put things into an `/etc/nginx` directory that doesn't exist.

The error says that it's failing at `opsworks_ruby/libraries/drivers_webserver_nginx.rb:56:in `add_ssl_directory'`, so it's definitely getting into `opsworks_ruby` code for `nginx` somehow.

I realize now that I said it was in the 'configure' _step_, but what I should have said is that the log snippet came from the 'configure' _log_ inside of OpsWorks. I have no idea what actual step within `opsworks_ruby` is triggering it. Based on the fact that I had to create `/etc/nginx/sites-available` and `/etc/nginx/sites-enabled` to get around the problem I'm thinking it might be somewhere in the application deployment part of `opsworks_ruby`.

**Comment by phongsi** [comment]
So since it's running the nginx webserver code, it's definitely not the null webserver that got instantiated.

I'm able to get this to work for me. I'm using it in production on an opsworks stack in aws. My servers have no webserver or appserver. Just running workers.

I don't know what your code is doing, but my guess is still that your hitting this line
https://github.com/ajgon/opsworks_ruby/blob/master/libraries/drivers_webserver_factory.rb#L15

If you're using berkshelf, you can point to your own version of this cookbook. Try putting log statements to find out if your overrides are really working or not. It sounds like your overrides aren't working.

Also I looked at your logs more closely. Unicorn was and is being built, so you're override for that doesn't work either. If the null appserver was really instantiating, you will not see unicorn in your logs. for example the first line you pasted
```
[2016-08-25T19:41:10+00:00] INFO: template[/srv/www/report_convertor/shared/config/unicorn.conf] created file /srv/www/report_convertor/shared/config/unicorn.conf
```
shouldn't happen.

**Comment by jagthedrummer** [comment]
Weird. With the referenced attribute lines unicorn doesn't start for me, but if I disable the line it does start. I'll add some logging and try to figure out what's up.

**Comment by phongsi** [comment]
great post your findings and keep us updated

**Comment by jagthedrummer** [comment]
@phongsi I suspect that this is a problem with how I'm installing/configuring opsworks_ruby. Could you give me a general idea of what I should be doing? (The docs seem to pretty much assume that the reader is a seasoned chef pro, and I, unfortunately, am not a seasoned chef pro.)

I had an existing chef repo from using chef 11 on OpsWorks. To move to chef 12 I added a `Berksfile`, and added this line to the bottom of it

```
cookbook "opsworks_ruby"
```

Then I added the recipes to the appropriate steps in my OpsWorks layer. (`opsworks_ruby::setup` - attach to Setup, etc...)

Everything worked OK at that point, but I had unicorn and nginx running, which I'd rather not have.

So I added another cookbook to my repo, named 'report_convertor', and then added these lines to the `attributes/default.rb` file in that cookbook:

```
default['deploy']['report_convertor']['appserver']['adapter'] = 'null' # Don't run unicorn
default['deploy']['report_convertor']['webserver']['adapter'] = 'null' # Don't run nginx
```

As I mentioned before, this _seems_ to at least halfway work. When chef runs with those two attribute lines in place `/etc/nginx` is not created, and unicorn is not started. (I can't find evidence on either unicorn or nginx being installed anywhere on the box.) However, it does seem that opsworks_ruby still attempts to configure both unicorn and nginx. If I remove those two lines `/etc/nginx` IS created and I can find unicorn and nginx binaries on the system, and they're both running by default.

**Comment by ajgon** [comment]
Hey @jagthedrummer 

You don't need to create any additional recipes to use this cookbook (as long as you don't need any extra actions). All those parameters are configurable via "Stack JSON" in AWS Opsworks Panel. You can find it in `Stack -> Stack Settings -> Edit` and then `Custom JSON` (if you wish to configure it on the whole stack level), or under `Layer -> Settings` also `Custom JSON` field (if you wish to configure them on layer settings). Then you can pass those parameters as a simple json data, so in you example:

```json
{
  "deploy': {
    "report_convertor": {
      "appserver": {
        "adapter": "null"
      },
      "webserver": {
        "adapter": "null"
      },
    }
  }
}
```

and you should be good to go!

**Comment by jagthedrummer** [comment]
Ah-ha! Thanks for the tip, @ajgon. I tried that and it worked like a charm.

The docs don't make it at all clear that you can configure the cookbook this way. Would you be open to accepting a PR that adds this info to the README?

**Comment by ajgon** [comment]
Sure, go ahead :)
