### ISSUE TITLE
Bundler is unable to install gems from private repositories

### ISSUE THREAD

**Issue by olbrich** [ajgon/opsworks_ruby#37]
When installing an app, I get failures during the deploy phase while it's trying to bundle.  The errors indicate that bundler is unable to checkout code from several private repositories that we maintain.

It appears that during the initial checkout of code, the `Drivers::Scm::Git` class adds a wrapper that injects the deploy key so that the initial checkout can occur.  

This does not happen during the `perform_bundle_install` call in the deploy recipe, and as such the deploy user does not have access to the appropriate keys.

**Comment by ajgon** [comment]
Hey @olbrich 

I implemented a quick fix. Since I don't have access to private gem repositories, can you please check out this cookbook from `master` and see if it works?

**Comment by olbrich** [comment]
@ajgon Thanks, I managed to work around this a bit yesterday and ran into a related problem.... the bundle run doesn't specify the user to be node['deployer']['user'].

**Comment by ajgon** [comment]
Tested against private repos - works fine.
