### ISSUE TITLE
Do not drop database when migration fails

### ISSUE THREAD

**Issue by marcosbeirigo** [ajgon/opsworks_ruby#58]
https://github.com/ajgon/opsworks_ruby/blob/master/attributes/default.rb#L103

I know this is handy because it creates your database when it is missing but it is also extremely dangerous.

Here's an example:
Since we deploy our stack on many instances, chances that more than one of them will run migrations at the same time are quite high. If migration fails, `db:setup`  will try to recreate the database by dropping it if it exists. you don't want to do that on production.

**Comment by mberlanda** [comment]
@marcosbeirigo I see you are an active contributor of this repo. Could you maybe help me to figure out what is wrong with #57 ?

Regarding your issue, I see your point but I guess that in this specific case, you can just override the default `migration_command` in the custom JSON.

**Comment by ajgon** [comment]
Sorry for late reply, I was on my long-deserved vacation and came back yesterday :)

This is really nice catch, with serious implications - thank you for pointing that out! I fixed it, and released a new version.

**Comment by inket** [comment]
I have also lost production data because of this issue on the latest version. (my fault for not realizing the data was lost on staging too...)

I think running `db:setup` just because `db:version` failed is still to general.

How about something like this?

```bash
if [[ $(/usr/local/bin/bundle exec rake db:version 2>&1) == *"ActiveRecord::NoDatabaseError"* ]]; then 
  /usr/local/bin/bundle exec rake db:setup;
else
  /usr/local/bin/bundle exec rake db:migrate;
fi
```

**Comment by marcosbeirigo** [comment]
@inket wasn't this fixed last year? are you running the last version of the recipe?

**Comment by inket** [comment]
I thought it was fixed too. I am running a fork of the latest version of the recipe which dumps the output of `db:version` into a log file instead.

```ruby
default['defaults']['framework']['migration_command'] =
  'if /usr/local/bin/bundle exec rake db:version > log/db-version.log 2>&1; ' \
  'then /usr/local/bin/bundle exec rake db:migrate; ' \
  'else /usr/local/bin/bundle exec rake db:setup; ' \
  'fi'
```

But this shouldn't matter. The logic for running `db:setup` when `db:version` fails for any reason is not ideal. A gem misconfiguration or a random error could cause `db:setup` to run on production.

Limiting it to `ActiveRecord::NoDatabaseError` should be safer.

**Comment by marcosbeirigo** [comment]
Agree. I actually think we should remove db::setup altogether. It's not that much of a hassle to create the database manually. Sorry about your database man, hope you had a backup.

**Comment by inket** [comment]
Thanks. I did have an RDS snapshot and not much was lost so it's no biggie.

Let's see what @ajgon thinks! 😄

**Comment by inopinatus** [comment]
As a general design principle, it's okay to have potentially very destructive actions in your automation code, but they must be guarded by an explicit flag that enables them, absent which an informative exception occurs. 

In this case I'd suggest it be something only set via per-action custom json.

For comedy value I have known people use values like { "authorisation": "Picard 4-7 Alpha Tango" } or for better certainty of intention make it match the current date, which guards against inadvertent use of such codes in stack json.

**Comment by ajgon** [comment]
I agree, that this is risky behavior, but I also want to keep it as automated as possible :)
Maybe I should switch the command from `rake db:setup` to `rake db:create db:migrate db:seed` - which is practically the same as `db:setup` minus the `db:drop` part. However I see some implications:

* this would take longer, since all migrations needs to be run, instead of simple schema load. 
* poorly written migrations would fail when setting up the new instance (for example somebody used a model logic in a migration, but later in the project the model was removed) - however that should be developers problem, not cookbooks, as migrations should always pass (on the way up at least)

As another precaution I would also add the extended `if` statement which @inket proposed.

What do you guys think? This should be way safer, because in worst case scenario only seeds will be populated again.

**Comment by inket** [comment]
I tried the extended `if` for about a couple of days, and it's been working fine. I can see it working as expected, but my team and I decided to eliminate the `db:setup` completely and deal with new databases manually when needed (though I can see how that might not be best for this project)

**Comment by inket** [comment]
Small note if you do decide to use the `if [[ $(command) == *"substring"* ]]` variant:

This command is ran with `sh` and not `bash`, so it would cause a `sh: [[: command not found` error. Correct syntax for POSIX shell is

```sh
case $(command) in *"substring"*) echo "yep";; *) echo "nope";; esac
```
