### ISSUE TITLE
Dependency on nginx 2.7 is breaking berks

### ISSUE THREAD

**Issue by sethfloydjr** [ajgon/opsworks_ruby#65]
I started running into an issue today where berks install was timing out while trying to install opsworks_ruby. After a little digging I narrowed down the issue to this [issue with nginx cookbook](https://github.com/miketheman/nginx/issues/412). The solution so far (and this worked for me after I forked) is to change dependency from nginx to chef_nginx.

Im running...
Chef Development Kit Version:  #1.2.22
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 2017-02-17T15:06:01.341142 38350] 2017-02-17T15:06:01.341286 38350] 2017-02-17T15:06:01.341389 38350] 2017-02-17T15:06:01.341481 38350] 2017-02-17T15:06:01.372787 38350] 2017-02-17T15:06:01.372946 38350] 5.6.0
kitchen version: 1.15.0

**Comment by ecielam** [comment]
I'm running into the same issue when attempting to use the aws cookbook.  Solution is the same for me ... fork + change to chef_nginx.

**Comment by ajgon** [comment]
Thank you! I updated the dependencies.
