### ISSUE TITLE
Interest in replacing ruby-ng w/ rvm?

### ISSUE THREAD

**Issue by kpheasey** [ajgon/opsworks_ruby#67]
Currently, ruby is installed via brightbox (ruby-ng), these versions are not compiled with debug symbols which is necessary for thread profiling and you can't target patch level versions like 2.3.1.  Installing ruby with rvm includes the debug symbols and it also allows easier access to patch level versions (2.3.x)

I have successfully replaced ruby-ng with rvm, using a system wide install.  There are minimal code changes.  Would there be interest in a pull request?

I'm asking because I'm not sure if this is implementation specific.

**Comment by ajgon** [comment]
`ruby-ng` was chosen initially because it was easiest thing to do. However prepacked binaries are problematic, for reasons you mentioned, but also, different distros (amazon linux/ubuntu) have different versions available which causes consistency problems.

I'm really happy for rvm support, and will greatly appreciate the PR!

**Comment by kpheasey** [comment]
@ajgon How do I run the tests?  I have another open pull request that needs some specs too.  Once I update

**Comment by ajgon** [comment]
Assuming you have [chef-dk](https://downloads.chef.io/chefdk) installed:

```
chef exec bundle exec overcommit -r
chef exec bundle exec rspec # specs

# integration tests, needs vagrant and virtualbox installed
for i in default-ubuntu-1404 all-options-ubuntu-1404 unicorn-apache-hanami-resque-ubuntu-1404 thin-nginx-padrino-delayed-job-ubuntu-1404 nullified-ubuntu-1404; do kitchen destroy $i; kitchen converge $i; done
for i in default-ubuntu-1404 all-options-ubuntu-1404 unicorn-apache-hanami-resque-ubuntu-1404 thin-nginx-padrino-delayed-job-ubuntu-1404 nullified-ubuntu-1404; do kitchen verify $i; done
```

**Comment by kpheasey** [comment]
Thanks.  I'll use the circle ci output and your snippets to update any specs and get everything passing.

**Comment by kpheasey** [comment]
@ajgon I have everything pretty much ready to go, except for one test that's not passing:

https://github.com/ajgon/opsworks_ruby/blob/a89451f17d19e2d1b4974f23e8f4a546b8ba5b1d/test/integration/all_options/serverspec/all_options_spec.rb#L157-L159

I receive the following output:

```
       Failures:

         1) opsworks_ruby::deploy appserver Command "pgrep -f puma | tr '\n' ' '" stdout should match /(?:[0-9]+ ){4}/
            Failure/Error: its(:stdout) { should match(/(?:[0-9]+ ){4}/) }
              expected "381 383 " to match /(?:[0-9]+ ){4}/
              Diff:
              @@ -1,2 +1,2 @@
              -/(?:[0-9]+ ){4}/
              +"381 383 "

              /bin/sh -c pgrep\ -f\ puma\ \|\ tr\ \'\\n\'\ \'\ \'
              381 383
            # /tmp/verifier/suites/serverspec/all_options_spec.rb:158:in `block (4 levels) in <top (required)>'
```

I'm not really sure what that's testing though.  Puma is up and running without issue on my opsworks dev stack using ubuntu 14.04.

**Comment by shrinathaithal** [comment]
@kpheasey any chance you can find that branch again? The link above is 404 and I am in need of ruby 3. Brightbox is still at 2.7 :/

**Comment by ajgon** [comment]
@shrinathaithal Have you tried using `fullstaq` provider? They should have `3.x` ruby available. You need to set `ruby-provider` to `fullstaq` in your Custom JSON, and then you can set `ruby-version` to `3.0.1`.

**Comment by shrinathaithal** [comment]
I tried snap (hard coded in my own recipe and disabled ruby-ng
installations in my copy).
I found it had 3.0.1 and works for now.
But the inherent problem with snap modules is they upgrade without telling.
Will try out fullstaq, thank you.
