### ISSUE TITLE
Changing default['defaults']['appserver']['preload_app'] from true to false

### ISSUE THREAD

**Issue by kpheasey** [ajgon/opsworks_ruby#72]
The current `default['defaults']['appserver']['preload_app'] = true` causes 500 errors during deployments, between the time to server stops and it preloads.  Setting this to false eliminates the 500 error and instead there is a pause between requests while the process preloads the app.  I feel the temporary pause is a better end user experience compared to an nginx/apache 500 error.

Would you like me to create a PR for changing the default?

**Comment by ajgon** [comment]
I'm fine with that - the question is, would it apply for both `puma` and `unicorn` (since both of them uses this parameter)?

**Comment by kpheasey** [comment]
I'm not very familiar with unicorn and preloading.  I imagine it still takes some time to pre-load and the server won't respond until it's done. 

 Is there a test that makes sure the app server is responding after a deployment?  If so, all tests are passing when I make the change.

Do you use unicorn?  If so, do you get errors when refreshing a page during deployments?

**Comment by ajgon** [comment]
I switched to puma as well :) But if I remember correctly, disabling app preloading in unicorn caused problems. I'll do the research later this day and let you know.

**Comment by conarro** [comment]
Came across this issue doing some digging on this as well, and also found this comment so figured I'd share here:

https://github.com/puma/puma/blob/0ea7af5e2cc8fa192ec82934a4a47880bdb592f8/lib/puma/configuration.rb#L333-L335

@ajgon if you don't end up changing the default for the sake of Unicorn (which may end up making sense), it might help to at least mention this somewhere in the docs.

**Comment by kpheasey** [comment]
Changing from `false` to `true` does not actually prevent the 500 errors.  Each request that hangs is taking up a worker.  This means any request after all the workers have been used up will throw a 500.
