### ISSUE TITLE
Increasing Migration Timeout?

### ISSUE THREAD

**Issue by kpheasey** [ajgon/opsworks_ruby#74]
Is it possible to increase deployment timeouts?  I have migrations that can take 2-3 hours to run (adding col, changing index, etc, on 40+ million row tables).  Things seem to timeout after 10 minutes, but I can't find a limit or attribute set anywhere.

**Comment by ajgon** [comment]
Hah... good question. As far as I remember, I didn't implement anything like timeouts. Maybe it's a AWS "feature" ? Can you paste me example timeout error?

**Comment by kpheasey** [comment]
Here's the log from the failed deployment:

https://gist.github.com/kpheasey/e1715d7f1f72d1ae7e43cc4c799ec5c3

**Comment by ajgon** [comment]
It looks like internal `chef` timeout kicks in. There is a `timeout` option which can be added to `deploy.rb` recipe as described here: https://docs.chef.io/resource_deploy.html

However I am currently traveling and cannot adjust that until the beginning of an April. A quick hacky fix which I can suggest for now, is to add `timeout 86400` to the `deploy.rb` recipe in your `opsworks_ruby` cookbook and see if that helps. If it does - please let me know, I will parametrize this parameter when I get back 😃

**Comment by kpheasey** [comment]
That worked perfectly.  I'll create a pull request during the week.

https://github.com/kpheasey/opsworks_ruby/tree/timeout
