### ISSUE TITLE
Add SQLServer adpter support

### ISSUE THREAD

**Issue by mberlanda** [ajgon/opsworks_ruby#75]
Would it be possible to add support for *sql-server*?

I assume that I should create a `libraries/drivers_db_sqlserver.rb` as it follows:

```rb
# libraries/drivers_db_sqlserver.rb
module Drivers
  module Db
    class Sqlserver < Base
      adapter :sqlserver
      allowed_engines # something goes here
      packages debian: 'mssql-server', rhel: 'mssql-server'
    end
  end
end
```
However, if I am not wrong, I would have to these packages to the repository:

- [MS debian instructions](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-ubuntu)
```
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server.list | sudo tee /etc/apt/sources.list.d/mssql-server.list
sudo apt-get update
sudo apt-get install -y mssql-server
```
- [MS  rhel instructions](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-red-hat)
```
sudo su
curl https://packages.microsoft.com/config/rhel/7/mssql-server.repo > /etc/yum.repos.d/mssql-server.repo
exit
sudo yum install -y mssql-server
```

In order to run **mysql-server** locally, I am using those two gems:
- [`gem 'activerecord-sqlserver-adapter'`](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter) 
- [`gem 'tiny_tds'`](https://github.com/rails-sqlserver/tiny_tds)

Do you have any suggestion about how to proceed?
I would be pleased to make a fork and contribute to this project!

**Comment by ajgon** [comment]
`allowed_engines` are used by `opsworks_ruby` to determine which SQL driver load internally, basing on the configuration. There can be two ways of configuring database - either by the OpsWorks itself (it attaches layers to desired RDS instances), or via `app['database']['adapter']` node option.

If I remember correctly, AWS doesn't support SQL Server out of the box, which is good, because it leaves the "AWS part" out of equation. So all you have to do, is to determine how do you want your adapter to be called (I suggest to use just `sqlserver`), and then, end-user would have to provide this as a `app['database']['adapter']` option).

Adding custom repos, would be slightly more complicated, as you need to implement `setup` method in your driver, and add them there using [`apt_repository`](https://docs.chef.io/resource_apt_repository.html) and [`yum_repository`](https://docs.chef.io/resource_yum_repository.html) helpers. Please keep in mind, that methods themselves doesn't work there, you need to use chef `context` variable each time you wish to invoke something from chef, for example:

```def setup
  context.apt_repository <yada, yada, yada>
end```

If you need any extra help, just let me know! And good luck! 😄

**Comment by mberlanda** [comment]
Hi @ajgon, thank you so much for your quick and detailed reply!
I have started to work on [my fork](https://github.com/mberlanda/opsworks_ruby/tree/sqlserver) writing the driver.

I am having some troubles trying to find out how to compose my setup method. 
```rb
def setup
  context.apt_repository 'mssql-server' do
    key 'https://packages.microsoft.com/keys/microsoft.asc'
  end
end
```
I am having a look to all the options comparing them to the install process on ubuntu:
`curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -`

- `keyserver`: The GPG keyserver where the key for the repo should be retrieved. Default value: “keyserver.ubuntu.com”.
- `key`: If a keyserver is provided, this is assumed to be the fingerprint; otherwise it can be either the URI to the GPG key for the repo, or a cookbook_file. Default value: nil.
- `key_proxy`: If set, a specified proxy is passed to GPG via http-proxy=. Default value: nil.

`curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server.list | sudo tee /etc/apt/sources.list.d/mssql-server.list`

This instruction seems to be too strictly to  ubuntu version 16.04. I am not sure about how to make it more generic

`sudo apt-get install -y mssql-server`

How can I trigger them? How do you proceed when you install the other database type?
Should I install all of this package or would you suggest an easier way?

Do you think that it could be easier to find and integrate some other cookbooks eventually?
e.g. [https://supermarket.chef.io/cookbooks/sql_server](https://supermarket.chef.io/cookbooks/sql_server) - a windows example

Thank you in advance
Mauro

**Comment by ajgon** [comment]
Hey, sorry for late reply - I was traveling and moving to a new apartment :)

Anyway, the thing is - this cookbook doesn't install any database for any configuration. It solely relies on externally provided DB. Which means, it expects either configured RDS which is enabled in OpsWorks, or some other machine with DB instance, and credentials given in Custom JSON.

So I think, the approach which you try to achieve is problematic in general - maybe the better solution is to add the driver, and let the user configure sql-server by himself? (either by adding a custom/supermarket sql-server cookbook, or by using a completely different machine and connect to it, using `app['database']` options).

**Comment by mberlanda** [comment]
Hi @ajgon , don't worry about the delay! I hope that all went fine.

Actually I was trying hard to get my recipe working but I probably wasn't following an efficient approach.
I would rather let the user specify all the information needed by the db to work. 

For instance, in the local app I have created for testing a SQL server connection, my `config/database.yml` looks like:

```yml
default: &default
  adapter: sqlserver
  # encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: username
  password: password

development:
  <<: *default
  database: name_development
  mode: dblib
  host: 127.0.0.1
  port: "1433"
  timeout: 20 
```

So I can imagine that my configuration JSON will take a little more arguments than the one you provided [here](http://opsworks-ruby.rzegocki.pl/configuration-builder). E.g.

```json
{
  "application_short_name": {
    "database": {
      "adapter": "mssql-server",
      "username": "username",
      "password": "pass",
      "host": "127.0.0.1",
      "database": " name_development"
      "port": "1433",
      "mode": "dblib",
      "timeout": 20
    }
  }
}
```

If I wnat to proceed in this way, can I ignore the `packages` part in the driver? If I pass additional elements to the `database` key of the custom JSON, should I edit something or you all already taking any key without validation?

Thank you very much

Mauro

**Comment by ajgon** [comment]
If you want, just to use the `database.yml` then you can ignore whole packages (and setup) part completely. You just need to create another driver, and set the `adapter` and `allowed_engines` (which should be the same). And it should work out of the box :)

Also, please add the info to the documentation, and mention, that this is Custom JSON only (i.e. no RDS support in Amazon) adapter.

**Comment by ajgon** [comment]
Closing this, as the thread is old and dead. If you any other questions, feel free to ask them here.
