### ISSUE TITLE
config/puma.rb usage?

### ISSUE THREAD

**Issue by kpheasey** [ajgon/opsworks_ruby#77]
Is it possible to use a config/puma.rb file to control things like worker and thread counts?

I'm in the process of optimizing a web server and I'm not sure if making changes here is having an effect, or I need to specify them in custom json.

**Comment by ajgon** [comment]
Yes, you can configure plenty of them - https://opsworks-ruby.readthedocs.io/en/latest/attributes.html#puma

**Comment by kpheasey** [comment]
Can I use the actional config/puma.rb file in my application, or do I have to use custom json?

Does the custom json take affect on app deployment,  or do I need to run another command?

**Comment by ajgon** [comment]
`opsworks_ruby` will create `puma.rb` for you: [libraries/drivers_appserver_base.rb#L65](https://github.com/ajgon/opsworks_ruby/blob/master/libraries/drivers_appserver_base.rb#L65), [libraries/drivers_appserver_puma#L9](https://github.com/ajgon/opsworks_ruby/blob/master/libraries/drivers_appserver_puma.rb#L9) and [templates/default/puma.rb.erb](https://github.com/ajgon/opsworks_ruby/blob/master/templates/default/puma.rb.erb). As you may notice, your `puma.rb` is not taken into consideration as the deamon is fired up against pregenerated config ([libraries/drivers_appserver_puma#L13](https://github.com/ajgon/opsworks_ruby/blob/master/libraries/drivers_appserver_puma.rb#L13)). 

To make this work you have to either overwrite the `appserver_command` method with your path, or iplement a new configuration option.
