### ISSUE TITLE
Rails app log rotation

### ISSUE THREAD

**Issue by mattboldt** [ajgon/opsworks_ruby#78]
It'd be nice to include automatic log rotation for the `/srv/www/<app name>/shared/log/` dir. Our servers filled up in disk space due to this.

I've got a busy week ahead of me, so I don't know if I can make a pull with this, but I can try.

**Comment by ajgon** [comment]
Shouldn't this be handled by another cookbook, i.e. [logrotate](https://supermarket.chef.io/cookbooks/logrotate) or similar?

**Comment by mattboldt** [comment]
Yeah, that's what I ended up using. But in the spirit of trying to replicate the old Chef 11 OpsWorks Rails setup, I'd expect it to also be included.

**Comment by mattboldt** [comment]
Awesome! Thanks so much. Do you plan on pushing a new tag / release?

**Comment by ajgon** [comment]
Yes, probably on weekend

**Comment by bakongo** [comment]
Nice! This will come in useful.

**Comment by ajgon** [comment]
[Released](https://supermarket.chef.io/cookbooks/opsworks_ruby)

**Comment by olbrich** [comment]
Sorry I missed this one, but I think it's outside the scope of what this cookbook should be handling.
Are you going to add support for `ntp` when folks realize their clocks are drifting? Or `swap_tuning` when the instance runs out of memory?

**Comment by ajgon** [comment]
No, and no. But I see your point here. However, the logrotate was in fact in original Chef 11 recipes, and the main goal of this cookbook is to mimic the AWS version as closely as possible.

**Comment by andrewyoo** [comment]
@ajgon just wanted to start with thanks. I've been one of the users waiting around forever for ruby 2.4 support.

I've been testing this cookbook and it working well for me on my staging env.  I did notice, that for this log rotate feature, it does not rotate all the logs in app/log but only the rails log file.  I'm not very experienced in chef, but how could i get it to rotate all logs in app/log?

**Comment by andrewyoo** [comment]
@ajgon thanks for this fix
