### ISSUE TITLE
Question: sidekiq usage

### ISSUE THREAD

**Issue by mattboldt** [ajgon/opsworks_ruby#79]
Following the code from here: https://github.com/ajgon/opsworks_ruby/blob/883588ff000043d855ea36502ac2e4e58761914f/attributes/default.rb#L116

I have this sidekiq config:
```json
      "worker": {
        "adapter": "sidekiq",
        "config": {
          "concurrency": 5,
          "verbose": false,
          "queues": ["critical", "default", "low"]
        }
      }
```

However, I'd like to specify config for each of the 2 processes like this:
```json
     "worker1": {
        "process_count": 1,
        "config" : {
          "concurrency": 5,
          "verbose": false,
          "queues": ["critical", "default", "low"]
        }
      },
      "worker2": {
        "process_count": 1,
        "config" : {
          "concurrency": 1,
          "verbose": false,
          "queues": ["single_file"]
        }
      }
```

Is there any way to do this currently?

**Comment by kpheasey** [comment]
I don't believe you can do that.

Processes are unique by layer.  You cannot run two layers on the same instance since the configuration and deployments will cancel each other out.

**Comment by mattboldt** [comment]
@kpheasey for reference, I'm coming from this older OpsWorks cookbook

https://github.com/drakerlabs/opsworks_sidekiq#custom-json

**Comment by ajgon** [comment]
[Created branch with experimental support](https://github.com/ajgon/opsworks_ruby/tree/sidekiq/multiple-configs). There, you need to pass an array of configs, so for your example:
```json
     "worker": {
        "process_count": 1,
        "config" : [
          {
            "concurrency": 5,
            "verbose": false,
            "queues": ["critical", "default", "low"]
          },
          {
            "concurrency": 1,
            "verbose": false,
            "queues": ["single_file"]
          }
        ]
      }
```

However, haven't tested it on my environment - please let me know, if it works for you, and if it does - I'll merge it to the `master`.

**Comment by kpheasey** [comment]
@ajgon Was this merged in?

**Comment by ajgon** [comment]
No. It's still in the experimental branch, since it's a breaking change. I can't test it currently on my environment, so if you want to use it, please check it out and let me know if it works for you.

**Comment by dotnofoolin** [comment]
Sorry to reply to an old issue, but it describes what I'm trying to do. Run specific workers with specific queues. I want to have one delayed_job worker only act on a certain queue, and the other worker act on another queue.

Since the branch above was going to be a breaking change, could a new key be added instead of using "worker". Like maybe "workers" or "worker_with_config"?

**Comment by ajgon** [comment]
The branch is so old, that is probably impossible to adapt it to the current codebase. However it can be used as a base for a new PR if necessary. Unfortunately, I don't have a time recently to build this, but PRs are very welcome :)
