### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by kpheasey** [ajgon/opsworks_ruby#84]
Since the latest release would break all existing installations, should it be labeled 2.0?  If I hadn't seen the release email, I would have been in trouble when I updated my cookbooks next.

**Comment by ajgon** [comment]
In theory it shouldn't break anything - I just dropped the support for all distros, but the cookbook should still work on 14.04 and 12.04. However to be honest, didn't test that. Have you? If yes, and they break - then I 100% agree - the version should be bumped to 2.x.

**Comment by kpheasey** [comment]
No, I haven't tested yet. I'll check it out on Monday.

**Comment by kpheasey** [comment]
I tested on Ubuntu 14.04 and everything is good.

**Comment by ajgon** [comment]
RIght on! Thank you! 👍
