### ISSUE TITLE
Unicorn processes inheriting root env

### ISSUE THREAD

**Issue by andrewyoo** [ajgon/opsworks_ruby#85]
Not sure if this was intended, but I thought I'd start a conversation about it just in case since it took me like an hour to figure out what's going on.

I was using pdfkit gem which calls ```` `bundle exec which wkhtmltopdf` ```` to find the binary.
From my unicorn workers, this command was erroring, because ````bundle exec```` looks up ````Gem.user_home```` which uses the ENV['home'] which was set to /root and not /home/deploy. 

I think the unicorns are started up as root then transferred to user deploy, but this causes ENV['home'] and ENV['USER'] to belong to root.  I "fixed" this eventually by just overriding ENV['home'] in my app env.

Should these processes be started natively as deploy?

**Comment by ajgon** [comment]
I checked it on `Chef 11` stack on AWS, and you're correct - everything should be ran in `deploy` user context (actually for obvious reasons if you think about it). Fix is on its way.
