### ISSUE TITLE
Installing other recipes and best practices with Chef and Opsworks

### ISSUE THREAD

**Issue by pjammer** [ajgon/opsworks_ruby#90]
Most apps that deal with thumbnails need ImageMagick and I also need to add a `yarn` recipe. 

Am I missing where, and if so what, to put these two include statements?  Should I just add a separate cookbook during setup or configure?  Is there some hook like `default[:application][:include_recipes = [:imagemagick, :yarn]` in a file I can't find?

Open to any suggestions as this gem is great and this is the only place for help that can make it even better. Thanks!

**Comment by ajgon** [comment]
Hey,

Regarding the packages - yes you need a separate cookbook, [I recommend this one](https://supermarket.chef.io/cookbooks/packages). Regarding `yarn` - you can install it using two different methods, [I described it here](https://github.com/ajgon/opsworks_ruby/issues/80).
